package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ActivagestorId generated by hbm2java
 */
public class ActivagestorId implements java.io.Serializable {

	private int consecutivo;
	private String documento;
	private Date fecha;

	public ActivagestorId() {
	}

	public ActivagestorId(int consecutivo, String documento, Date fecha) {
		this.consecutivo = consecutivo;
		this.documento = documento;
		this.fecha = fecha;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActivagestorId))
			return false;
		ActivagestorId castOther = (ActivagestorId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getDocumento() == castOther.getDocumento()) || (this.getDocumento() != null
						&& castOther.getDocumento() != null && this.getDocumento().equals(castOther.getDocumento())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37 * result + (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
