package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Activacion generated by hbm2java
 */
public class Activacion implements java.io.Serializable {

	private int consecutivo;
	private Actestado actestado;
	private Banco banco;
	private Gestor gestor;
	private Promotor promotor;
	private String cedula;
	private String nombre;
	private Date fechareg;
	private String usuarioreg;
	private String correo;
	private String clave;
	private String usuario;
	private String llave;
	private Integer ano;
	private String usuariomod;
	private Date fechacita;
	private Date fechaact;
	private Date fechamod;
	private Boolean ingresocadivi;
	private Boolean documentoscompletos;
	private Boolean citaasignada;
	private String agencia;
	private String tipoviaje;
	private Date fechainicioviaje;
	private Date fechafinviaje;
	private String clavemercantil;
	private Boolean coordenadas;
	private String provinet;
	private String claveprovinet;
	private Boolean rusad;
	private Boolean noingresacadivi;
	private Boolean rif;
	private String deposito;
	private Date fechadeposito;
	private BigDecimal valordeposito;
	private Date fechadevolucion;
	private BigDecimal valordevolucion;
	private Boolean erroringresocadivi;
	private Integer cupoaprobado;
	private String usuariobanco;
	private Boolean ingresobancalinea;
	private Boolean noingresobancalinea;
	private Integer destino;
	private Set erroringresocadivis = new HashSet(0);
	private Set estadoactivacions = new HashSet(0);
	private Set citas = new HashSet(0);
	private Set activagestors = new HashSet(0);
	private Set observacions = new HashSet(0);
	private Set viajes = new HashSet(0);

	public Activacion() {
	}

	public Activacion(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Activacion(int consecutivo, Actestado actestado, Banco banco, Gestor gestor, Promotor promotor,
			String cedula, String nombre, Date fechareg, String usuarioreg, String correo, String clave, String usuario,
			String llave, Integer ano, String usuariomod, Date fechacita, Date fechaact, Date fechamod,
			Boolean ingresocadivi, Boolean documentoscompletos, Boolean citaasignada, String agencia, String tipoviaje,
			Date fechainicioviaje, Date fechafinviaje, String clavemercantil, Boolean coordenadas, String provinet,
			String claveprovinet, Boolean rusad, Boolean noingresacadivi, Boolean rif, String deposito,
			Date fechadeposito, BigDecimal valordeposito, Date fechadevolucion, BigDecimal valordevolucion,
			Boolean erroringresocadivi, Integer cupoaprobado, String usuariobanco, Boolean ingresobancalinea,
			Boolean noingresobancalinea, Integer destino, Set erroringresocadivis, Set estadoactivacions, Set citas,
			Set activagestors, Set observacions, Set viajes) {
		this.consecutivo = consecutivo;
		this.actestado = actestado;
		this.banco = banco;
		this.gestor = gestor;
		this.promotor = promotor;
		this.cedula = cedula;
		this.nombre = nombre;
		this.fechareg = fechareg;
		this.usuarioreg = usuarioreg;
		this.correo = correo;
		this.clave = clave;
		this.usuario = usuario;
		this.llave = llave;
		this.ano = ano;
		this.usuariomod = usuariomod;
		this.fechacita = fechacita;
		this.fechaact = fechaact;
		this.fechamod = fechamod;
		this.ingresocadivi = ingresocadivi;
		this.documentoscompletos = documentoscompletos;
		this.citaasignada = citaasignada;
		this.agencia = agencia;
		this.tipoviaje = tipoviaje;
		this.fechainicioviaje = fechainicioviaje;
		this.fechafinviaje = fechafinviaje;
		this.clavemercantil = clavemercantil;
		this.coordenadas = coordenadas;
		this.provinet = provinet;
		this.claveprovinet = claveprovinet;
		this.rusad = rusad;
		this.noingresacadivi = noingresacadivi;
		this.rif = rif;
		this.deposito = deposito;
		this.fechadeposito = fechadeposito;
		this.valordeposito = valordeposito;
		this.fechadevolucion = fechadevolucion;
		this.valordevolucion = valordevolucion;
		this.erroringresocadivi = erroringresocadivi;
		this.cupoaprobado = cupoaprobado;
		this.usuariobanco = usuariobanco;
		this.ingresobancalinea = ingresobancalinea;
		this.noingresobancalinea = noingresobancalinea;
		this.destino = destino;
		this.erroringresocadivis = erroringresocadivis;
		this.estadoactivacions = estadoactivacions;
		this.citas = citas;
		this.activagestors = activagestors;
		this.observacions = observacions;
		this.viajes = viajes;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Actestado getActestado() {
		return this.actestado;
	}

	public void setActestado(Actestado actestado) {
		this.actestado = actestado;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Gestor getGestor() {
		return this.gestor;
	}

	public void setGestor(Gestor gestor) {
		this.gestor = gestor;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechareg() {
		return this.fechareg;
	}

	public void setFechareg(Date fechareg) {
		this.fechareg = fechareg;
	}

	public String getUsuarioreg() {
		return this.usuarioreg;
	}

	public void setUsuarioreg(String usuarioreg) {
		this.usuarioreg = usuarioreg;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getLlave() {
		return this.llave;
	}

	public void setLlave(String llave) {
		this.llave = llave;
	}

	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Date getFechacita() {
		return this.fechacita;
	}

	public void setFechacita(Date fechacita) {
		this.fechacita = fechacita;
	}

	public Date getFechaact() {
		return this.fechaact;
	}

	public void setFechaact(Date fechaact) {
		this.fechaact = fechaact;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public Boolean getIngresocadivi() {
		return this.ingresocadivi;
	}

	public void setIngresocadivi(Boolean ingresocadivi) {
		this.ingresocadivi = ingresocadivi;
	}

	public Boolean getDocumentoscompletos() {
		return this.documentoscompletos;
	}

	public void setDocumentoscompletos(Boolean documentoscompletos) {
		this.documentoscompletos = documentoscompletos;
	}

	public Boolean getCitaasignada() {
		return this.citaasignada;
	}

	public void setCitaasignada(Boolean citaasignada) {
		this.citaasignada = citaasignada;
	}

	public String getAgencia() {
		return this.agencia;
	}

	public void setAgencia(String agencia) {
		this.agencia = agencia;
	}

	public String getTipoviaje() {
		return this.tipoviaje;
	}

	public void setTipoviaje(String tipoviaje) {
		this.tipoviaje = tipoviaje;
	}

	public Date getFechainicioviaje() {
		return this.fechainicioviaje;
	}

	public void setFechainicioviaje(Date fechainicioviaje) {
		this.fechainicioviaje = fechainicioviaje;
	}

	public Date getFechafinviaje() {
		return this.fechafinviaje;
	}

	public void setFechafinviaje(Date fechafinviaje) {
		this.fechafinviaje = fechafinviaje;
	}

	public String getClavemercantil() {
		return this.clavemercantil;
	}

	public void setClavemercantil(String clavemercantil) {
		this.clavemercantil = clavemercantil;
	}

	public Boolean getCoordenadas() {
		return this.coordenadas;
	}

	public void setCoordenadas(Boolean coordenadas) {
		this.coordenadas = coordenadas;
	}

	public String getProvinet() {
		return this.provinet;
	}

	public void setProvinet(String provinet) {
		this.provinet = provinet;
	}

	public String getClaveprovinet() {
		return this.claveprovinet;
	}

	public void setClaveprovinet(String claveprovinet) {
		this.claveprovinet = claveprovinet;
	}

	public Boolean getRusad() {
		return this.rusad;
	}

	public void setRusad(Boolean rusad) {
		this.rusad = rusad;
	}

	public Boolean getNoingresacadivi() {
		return this.noingresacadivi;
	}

	public void setNoingresacadivi(Boolean noingresacadivi) {
		this.noingresacadivi = noingresacadivi;
	}

	public Boolean getRif() {
		return this.rif;
	}

	public void setRif(Boolean rif) {
		this.rif = rif;
	}

	public String getDeposito() {
		return this.deposito;
	}

	public void setDeposito(String deposito) {
		this.deposito = deposito;
	}

	public Date getFechadeposito() {
		return this.fechadeposito;
	}

	public void setFechadeposito(Date fechadeposito) {
		this.fechadeposito = fechadeposito;
	}

	public BigDecimal getValordeposito() {
		return this.valordeposito;
	}

	public void setValordeposito(BigDecimal valordeposito) {
		this.valordeposito = valordeposito;
	}

	public Date getFechadevolucion() {
		return this.fechadevolucion;
	}

	public void setFechadevolucion(Date fechadevolucion) {
		this.fechadevolucion = fechadevolucion;
	}

	public BigDecimal getValordevolucion() {
		return this.valordevolucion;
	}

	public void setValordevolucion(BigDecimal valordevolucion) {
		this.valordevolucion = valordevolucion;
	}

	public Boolean getErroringresocadivi() {
		return this.erroringresocadivi;
	}

	public void setErroringresocadivi(Boolean erroringresocadivi) {
		this.erroringresocadivi = erroringresocadivi;
	}

	public Integer getCupoaprobado() {
		return this.cupoaprobado;
	}

	public void setCupoaprobado(Integer cupoaprobado) {
		this.cupoaprobado = cupoaprobado;
	}

	public String getUsuariobanco() {
		return this.usuariobanco;
	}

	public void setUsuariobanco(String usuariobanco) {
		this.usuariobanco = usuariobanco;
	}

	public Boolean getIngresobancalinea() {
		return this.ingresobancalinea;
	}

	public void setIngresobancalinea(Boolean ingresobancalinea) {
		this.ingresobancalinea = ingresobancalinea;
	}

	public Boolean getNoingresobancalinea() {
		return this.noingresobancalinea;
	}

	public void setNoingresobancalinea(Boolean noingresobancalinea) {
		this.noingresobancalinea = noingresobancalinea;
	}

	public Integer getDestino() {
		return this.destino;
	}

	public void setDestino(Integer destino) {
		this.destino = destino;
	}

	public Set getErroringresocadivis() {
		return this.erroringresocadivis;
	}

	public void setErroringresocadivis(Set erroringresocadivis) {
		this.erroringresocadivis = erroringresocadivis;
	}

	public Set getEstadoactivacions() {
		return this.estadoactivacions;
	}

	public void setEstadoactivacions(Set estadoactivacions) {
		this.estadoactivacions = estadoactivacions;
	}

	public Set getCitas() {
		return this.citas;
	}

	public void setCitas(Set citas) {
		this.citas = citas;
	}

	public Set getActivagestors() {
		return this.activagestors;
	}

	public void setActivagestors(Set activagestors) {
		this.activagestors = activagestors;
	}

	public Set getObservacions() {
		return this.observacions;
	}

	public void setObservacions(Set observacions) {
		this.observacions = observacions;
	}

	public Set getViajes() {
		return this.viajes;
	}

	public void setViajes(Set viajes) {
		this.viajes = viajes;
	}

}
