package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Administrativo generated by hbm2java
 */
public class Administrativo implements java.io.Serializable {

	private String documento;
	private Personal personal;
	private BigDecimal comision;
	private String cargo;

	public Administrativo() {
	}

	public Administrativo(Personal personal) {
		this.personal = personal;
	}

	public Administrativo(Personal personal, BigDecimal comision, String cargo) {
		this.personal = personal;
		this.comision = comision;
		this.cargo = cargo;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public BigDecimal getComision() {
		return this.comision;
	}

	public void setComision(BigDecimal comision) {
		this.comision = comision;
	}

	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

}
