package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Agencia generated by hbm2java
 */
public class Agencia implements java.io.Serializable {

	private String nombre;

	public Agencia() {
	}

	public Agencia(String nombre) {
		this.nombre = nombre;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
