package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Arrastrador generated by hbm2java
 */
public class Arrastrador implements java.io.Serializable {

	private String documento;
	private Personal personal;
	private Set promotors = new HashSet(0);

	public Arrastrador() {
	}

	public Arrastrador(Personal personal) {
		this.personal = personal;
	}

	public Arrastrador(Personal personal, Set promotors) {
		this.personal = personal;
		this.promotors = promotors;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public Set getPromotors() {
		return this.promotors;
	}

	public void setPromotors(Set promotors) {
		this.promotors = promotors;
	}

}
