package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Asesor generated by hbm2java
 */
public class Asesor implements java.io.Serializable {

	private String documento;
	private Personal personal;
	private BigDecimal comision;
	private String telefonooficina;
	private String extension;
	private Set promotors = new HashSet(0);
	private Set envioses = new HashSet(0);

	public Asesor() {
	}

	public Asesor(Personal personal) {
		this.personal = personal;
	}

	public Asesor(Personal personal, BigDecimal comision, String telefonooficina, String extension, Set promotors,
			Set envioses) {
		this.personal = personal;
		this.comision = comision;
		this.telefonooficina = telefonooficina;
		this.extension = extension;
		this.promotors = promotors;
		this.envioses = envioses;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public BigDecimal getComision() {
		return this.comision;
	}

	public void setComision(BigDecimal comision) {
		this.comision = comision;
	}

	public String getTelefonooficina() {
		return this.telefonooficina;
	}

	public void setTelefonooficina(String telefonooficina) {
		this.telefonooficina = telefonooficina;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public Set getPromotors() {
		return this.promotors;
	}

	public void setPromotors(Set promotors) {
		this.promotors = promotors;
	}

	public Set getEnvioses() {
		return this.envioses;
	}

	public void setEnvioses(Set envioses) {
		this.envioses = envioses;
	}

}
