package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * AuditTarjeta generated by hbm2java
 */
public class AuditTarjeta implements java.io.Serializable {

	private AuditTarjetaId id;

	public AuditTarjeta() {
	}

	public AuditTarjeta(AuditTarjetaId id) {
		this.id = id;
	}

	public AuditTarjetaId getId() {
		return this.id;
	}

	public void setId(AuditTarjetaId id) {
		this.id = id;
	}

}
