package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * AuditGastos generated by hbm2java
 */
public class AuditGastos implements java.io.Serializable {

	private AuditGastosId id;

	public AuditGastos() {
	}

	public AuditGastos(AuditGastosId id) {
		this.id = id;
	}

	public AuditGastosId getId() {
		return this.id;
	}

	public void setId(AuditGastosId id) {
		this.id = id;
	}

}
