package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AuditUsuarioId generated by hbm2java
 */
public class AuditUsuarioId implements java.io.Serializable {

	private String usuario;
	private Date fecha;
	private Integer operacion;
	private String descripcion;
	private String ipcliente;

	public AuditUsuarioId() {
	}

	public AuditUsuarioId(String usuario, Date fecha) {
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public AuditUsuarioId(String usuario, Date fecha, Integer operacion, String descripcion, String ipcliente) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.operacion = operacion;
		this.descripcion = descripcion;
		this.ipcliente = ipcliente;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getOperacion() {
		return this.operacion;
	}

	public void setOperacion(Integer operacion) {
		this.operacion = operacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getIpcliente() {
		return this.ipcliente;
	}

	public void setIpcliente(String ipcliente) {
		this.ipcliente = ipcliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditUsuarioId))
			return false;
		AuditUsuarioId castOther = (AuditUsuarioId) other;

		return ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
				&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getOperacion() == castOther.getOperacion()) || (this.getOperacion() != null
						&& castOther.getOperacion() != null && this.getOperacion().equals(castOther.getOperacion())))
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getIpcliente() == castOther.getIpcliente()) || (this.getIpcliente() != null
						&& castOther.getIpcliente() != null && this.getIpcliente().equals(castOther.getIpcliente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getOperacion() == null ? 0 : this.getOperacion().hashCode());
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		result = 37 * result + (getIpcliente() == null ? 0 : this.getIpcliente().hashCode());
		return result;
	}

}
