package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * AuditUsuario generated by hbm2java
 */
public class AuditUsuario implements java.io.Serializable {

	private AuditUsuarioId id;

	public AuditUsuario() {
	}

	public AuditUsuario(AuditUsuarioId id) {
		this.id = id;
	}

	public AuditUsuarioId getId() {
		return this.id;
	}

	public void setId(AuditUsuarioId id) {
		this.id = id;
	}

}
