package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * AuditTransferencia generated by hbm2java
 */
public class AuditTransferencia implements java.io.Serializable {

	private AuditTransferenciaId id;

	public AuditTransferencia() {
	}

	public AuditTransferencia(AuditTransferenciaId id) {
		this.id = id;
	}

	public AuditTransferenciaId getId() {
		return this.id;
	}

	public void setId(AuditTransferenciaId id) {
		this.id = id;
	}

}
