package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * AuditTarjetaviaje generated by hbm2java
 */
public class AuditTarjetaviaje implements java.io.Serializable {

	private AuditTarjetaviajeId id;
	private Tarjeta tarjeta;
	private Viaje viaje;

	public AuditTarjetaviaje() {
	}

	public AuditTarjetaviaje(AuditTarjetaviajeId id, Tarjeta tarjeta, Viaje viaje) {
		this.id = id;
		this.tarjeta = tarjeta;
		this.viaje = viaje;
	}

	public AuditTarjetaviajeId getId() {
		return this.id;
	}

	public void setId(AuditTarjetaviajeId id) {
		this.id = id;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

}
