package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * AuditTransferenciaId generated by hbm2java
 */
public class AuditTransferenciaId implements java.io.Serializable {

	private int consecutivo;
	private BigDecimal preciobolivar;
	private String tipobolivar;
	private Long valorbolivar;
	private String numcuenta;
	private String numcuentapromotor;
	private String documentopromotor;
	private BigDecimal preciocompra;
	private BigDecimal precioasesor;
	private String usuariomod;
	private Date fechamod;

	public AuditTransferenciaId() {
	}

	public AuditTransferenciaId(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public AuditTransferenciaId(int consecutivo, BigDecimal preciobolivar, String tipobolivar, Long valorbolivar,
			String numcuenta, String numcuentapromotor, String documentopromotor, BigDecimal preciocompra,
			BigDecimal precioasesor, String usuariomod, Date fechamod) {
		this.consecutivo = consecutivo;
		this.preciobolivar = preciobolivar;
		this.tipobolivar = tipobolivar;
		this.valorbolivar = valorbolivar;
		this.numcuenta = numcuenta;
		this.numcuentapromotor = numcuentapromotor;
		this.documentopromotor = documentopromotor;
		this.preciocompra = preciocompra;
		this.precioasesor = precioasesor;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	public String getTipobolivar() {
		return this.tipobolivar;
	}

	public void setTipobolivar(String tipobolivar) {
		this.tipobolivar = tipobolivar;
	}

	public Long getValorbolivar() {
		return this.valorbolivar;
	}

	public void setValorbolivar(Long valorbolivar) {
		this.valorbolivar = valorbolivar;
	}

	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	public String getNumcuentapromotor() {
		return this.numcuentapromotor;
	}

	public void setNumcuentapromotor(String numcuentapromotor) {
		this.numcuentapromotor = numcuentapromotor;
	}

	public String getDocumentopromotor() {
		return this.documentopromotor;
	}

	public void setDocumentopromotor(String documentopromotor) {
		this.documentopromotor = documentopromotor;
	}

	public BigDecimal getPreciocompra() {
		return this.preciocompra;
	}

	public void setPreciocompra(BigDecimal preciocompra) {
		this.preciocompra = preciocompra;
	}

	public BigDecimal getPrecioasesor() {
		return this.precioasesor;
	}

	public void setPrecioasesor(BigDecimal precioasesor) {
		this.precioasesor = precioasesor;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditTransferenciaId))
			return false;
		AuditTransferenciaId castOther = (AuditTransferenciaId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getPreciobolivar() == castOther.getPreciobolivar())
						|| (this.getPreciobolivar() != null && castOther.getPreciobolivar() != null
								&& this.getPreciobolivar().equals(castOther.getPreciobolivar())))
				&& ((this.getTipobolivar() == castOther.getTipobolivar())
						|| (this.getTipobolivar() != null && castOther.getTipobolivar() != null
								&& this.getTipobolivar().equals(castOther.getTipobolivar())))
				&& ((this.getValorbolivar() == castOther.getValorbolivar())
						|| (this.getValorbolivar() != null && castOther.getValorbolivar() != null
								&& this.getValorbolivar().equals(castOther.getValorbolivar())))
				&& ((this.getNumcuenta() == castOther.getNumcuenta()) || (this.getNumcuenta() != null
						&& castOther.getNumcuenta() != null && this.getNumcuenta().equals(castOther.getNumcuenta())))
				&& ((this.getNumcuentapromotor() == castOther.getNumcuentapromotor())
						|| (this.getNumcuentapromotor() != null && castOther.getNumcuentapromotor() != null
								&& this.getNumcuentapromotor().equals(castOther.getNumcuentapromotor())))
				&& ((this.getDocumentopromotor() == castOther.getDocumentopromotor())
						|| (this.getDocumentopromotor() != null && castOther.getDocumentopromotor() != null
								&& this.getDocumentopromotor().equals(castOther.getDocumentopromotor())))
				&& ((this.getPreciocompra() == castOther.getPreciocompra())
						|| (this.getPreciocompra() != null && castOther.getPreciocompra() != null
								&& this.getPreciocompra().equals(castOther.getPreciocompra())))
				&& ((this.getPrecioasesor() == castOther.getPrecioasesor())
						|| (this.getPrecioasesor() != null && castOther.getPrecioasesor() != null
								&& this.getPrecioasesor().equals(castOther.getPrecioasesor())))
				&& ((this.getUsuariomod() == castOther.getUsuariomod()) || (this.getUsuariomod() != null
						&& castOther.getUsuariomod() != null && this.getUsuariomod().equals(castOther.getUsuariomod())))
				&& ((this.getFechamod() == castOther.getFechamod()) || (this.getFechamod() != null
						&& castOther.getFechamod() != null && this.getFechamod().equals(castOther.getFechamod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37 * result + (getPreciobolivar() == null ? 0 : this.getPreciobolivar().hashCode());
		result = 37 * result + (getTipobolivar() == null ? 0 : this.getTipobolivar().hashCode());
		result = 37 * result + (getValorbolivar() == null ? 0 : this.getValorbolivar().hashCode());
		result = 37 * result + (getNumcuenta() == null ? 0 : this.getNumcuenta().hashCode());
		result = 37 * result + (getNumcuentapromotor() == null ? 0 : this.getNumcuentapromotor().hashCode());
		result = 37 * result + (getDocumentopromotor() == null ? 0 : this.getDocumentopromotor().hashCode());
		result = 37 * result + (getPreciocompra() == null ? 0 : this.getPreciocompra().hashCode());
		result = 37 * result + (getPrecioasesor() == null ? 0 : this.getPrecioasesor().hashCode());
		result = 37 * result + (getUsuariomod() == null ? 0 : this.getUsuariomod().hashCode());
		result = 37 * result + (getFechamod() == null ? 0 : this.getFechamod().hashCode());
		return result;
	}

}
