package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Autovoz generated by hbm2java
 */
public class Autovoz implements java.io.Serializable {

	private int consecutivo;
	private Establecimiento establecimiento;
	private Tarjeta tarjeta;
	private Date fechatx;
	private String tipotx;
	private BigDecimal valortxpesos;
	private Date fechamod;
	private String usuariomod;
	private Integer numtransaccion;
	private String numautorizacion;
	private BigDecimal valor;
	private String asesor;

	public Autovoz() {
	}

	public Autovoz(int consecutivo, Establecimiento establecimiento, Tarjeta tarjeta, Date fechatx) {
		this.consecutivo = consecutivo;
		this.establecimiento = establecimiento;
		this.tarjeta = tarjeta;
		this.fechatx = fechatx;
	}

	public Autovoz(int consecutivo, Establecimiento establecimiento, Tarjeta tarjeta, Date fechatx, String tipotx,
			BigDecimal valortxpesos, Date fechamod, String usuariomod, Integer numtransaccion, String numautorizacion,
			BigDecimal valor, String asesor) {
		this.consecutivo = consecutivo;
		this.establecimiento = establecimiento;
		this.tarjeta = tarjeta;
		this.fechatx = fechatx;
		this.tipotx = tipotx;
		this.valortxpesos = valortxpesos;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
		this.numtransaccion = numtransaccion;
		this.numautorizacion = numautorizacion;
		this.valor = valor;
		this.asesor = asesor;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Date getFechatx() {
		return this.fechatx;
	}

	public void setFechatx(Date fechatx) {
		this.fechatx = fechatx;
	}

	public String getTipotx() {
		return this.tipotx;
	}

	public void setTipotx(String tipotx) {
		this.tipotx = tipotx;
	}

	public BigDecimal getValortxpesos() {
		return this.valortxpesos;
	}

	public void setValortxpesos(BigDecimal valortxpesos) {
		this.valortxpesos = valortxpesos;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Integer getNumtransaccion() {
		return this.numtransaccion;
	}

	public void setNumtransaccion(Integer numtransaccion) {
		this.numtransaccion = numtransaccion;
	}

	public String getNumautorizacion() {
		return this.numautorizacion;
	}

	public void setNumautorizacion(String numautorizacion) {
		this.numautorizacion = numautorizacion;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public String getAsesor() {
		return this.asesor;
	}

	public void setAsesor(String asesor) {
		this.asesor = asesor;
	}

}
