package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco implements java.io.Serializable {

	private String codbanco;
	private String nombrebanco;
	private Byte dias;
	private Boolean activo;
	private Set tasaeuropromotorparametros = new HashSet(0);
	private Set tasadolarparametros = new HashSet(0);
	private Set cuentapromotors = new HashSet(0);
	private Set porcentajecomisiontxparams = new HashSet(0);
	private Set tasadolarpromotorparametros = new HashSet(0);
	private Set porcentcomisiontxparampromos = new HashSet(0);
	private Set tarjetas = new HashSet(0);
	private Set tasaeuroparametros = new HashSet(0);
	private Set cuentas = new HashSet(0);
	private Set activacions = new HashSet(0);

	public Banco() {
	}

	public Banco(String codbanco, String nombrebanco) {
		this.codbanco = codbanco;
		this.nombrebanco = nombrebanco;
	}

	public Banco(String codbanco, String nombrebanco, Byte dias, Boolean activo, Set tasaeuropromotorparametros,
			Set tasadolarparametros, Set cuentapromotors, Set porcentajecomisiontxparams,
			Set tasadolarpromotorparametros, Set porcentcomisiontxparampromos, Set tarjetas, Set tasaeuroparametros,
			Set cuentas, Set activacions) {
		this.codbanco = codbanco;
		this.nombrebanco = nombrebanco;
		this.dias = dias;
		this.activo = activo;
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
		this.tasadolarparametros = tasadolarparametros;
		this.cuentapromotors = cuentapromotors;
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
		this.tarjetas = tarjetas;
		this.tasaeuroparametros = tasaeuroparametros;
		this.cuentas = cuentas;
		this.activacions = activacions;
	}

	public String getCodbanco() {
		return this.codbanco;
	}

	public void setCodbanco(String codbanco) {
		this.codbanco = codbanco;
	}

	public String getNombrebanco() {
		return this.nombrebanco;
	}

	public void setNombrebanco(String nombrebanco) {
		this.nombrebanco = nombrebanco;
	}

	public Byte getDias() {
		return this.dias;
	}

	public void setDias(Byte dias) {
		this.dias = dias;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Set getTasaeuropromotorparametros() {
		return this.tasaeuropromotorparametros;
	}

	public void setTasaeuropromotorparametros(Set tasaeuropromotorparametros) {
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
	}

	public Set getTasadolarparametros() {
		return this.tasadolarparametros;
	}

	public void setTasadolarparametros(Set tasadolarparametros) {
		this.tasadolarparametros = tasadolarparametros;
	}

	public Set getCuentapromotors() {
		return this.cuentapromotors;
	}

	public void setCuentapromotors(Set cuentapromotors) {
		this.cuentapromotors = cuentapromotors;
	}

	public Set getPorcentajecomisiontxparams() {
		return this.porcentajecomisiontxparams;
	}

	public void setPorcentajecomisiontxparams(Set porcentajecomisiontxparams) {
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
	}

	public Set getTasadolarpromotorparametros() {
		return this.tasadolarpromotorparametros;
	}

	public void setTasadolarpromotorparametros(Set tasadolarpromotorparametros) {
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
	}

	public Set getPorcentcomisiontxparampromos() {
		return this.porcentcomisiontxparampromos;
	}

	public void setPorcentcomisiontxparampromos(Set porcentcomisiontxparampromos) {
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
	}

	public Set getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Set tarjetas) {
		this.tarjetas = tarjetas;
	}

	public Set getTasaeuroparametros() {
		return this.tasaeuroparametros;
	}

	public void setTasaeuroparametros(Set tasaeuroparametros) {
		this.tasaeuroparametros = tasaeuroparametros;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

	public Set getActivacions() {
		return this.activacions;
	}

	public void setActivacions(Set activacions) {
		this.activacions = activacions;
	}

}
