package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Banner generated by hbm2java
 */
public class Banner implements java.io.Serializable {

	private int consecutivo;
	private String imagen;
	private String caption;
	private Boolean estado;
	private Date fechainicio;
	private Date fechafin;
	private String clase;

	public Banner() {
	}

	public Banner(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Banner(int consecutivo, String imagen, String caption, Boolean estado, Date fechainicio, Date fechafin,
			String clase) {
		this.consecutivo = consecutivo;
		this.imagen = imagen;
		this.caption = caption;
		this.estado = estado;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.clase = clase;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

}
