package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * BaucherId generated by hbm2java
 */
public class BaucherId implements java.io.Serializable {

	private int consecutivo;
	private String numautorizacion;

	public BaucherId() {
	}

	public BaucherId(int consecutivo, String numautorizacion) {
		this.consecutivo = consecutivo;
		this.numautorizacion = numautorizacion;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getNumautorizacion() {
		return this.numautorizacion;
	}

	public void setNumautorizacion(String numautorizacion) {
		this.numautorizacion = numautorizacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BaucherId))
			return false;
		BaucherId castOther = (BaucherId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getNumautorizacion() == castOther.getNumautorizacion())
						|| (this.getNumautorizacion() != null && castOther.getNumautorizacion() != null
								&& this.getNumautorizacion().equals(castOther.getNumautorizacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37 * result + (getNumautorizacion() == null ? 0 : this.getNumautorizacion().hashCode());
		return result;
	}

}
