package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Baucher generated by hbm2java
 */
public class Baucher implements java.io.Serializable {

	private BaucherId id;
	private Transaccion transaccion;
	private BigDecimal valor;

	public Baucher() {
	}

	public Baucher(BaucherId id, Transaccion transaccion) {
		this.id = id;
		this.transaccion = transaccion;
	}

	public Baucher(BaucherId id, Transaccion transaccion, BigDecimal valor) {
		this.id = id;
		this.transaccion = transaccion;
		this.valor = valor;
	}

	public BaucherId getId() {
		return this.id;
	}

	public void setId(BaucherId id) {
		this.id = id;
	}

	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
