package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Bloqueotarjeta generated by hbm2java
 */
public class Bloqueotarjeta implements java.io.Serializable {

	private int secuencia;
	private String numerotarjeta;
	private Integer consecutivo;
	private String observacion;
	private Date fecha;

	public Bloqueotarjeta() {
	}

	public Bloqueotarjeta(int secuencia) {
		this.secuencia = secuencia;
	}

	public Bloqueotarjeta(int secuencia, String numerotarjeta, Integer consecutivo, String observacion, Date fecha) {
		this.secuencia = secuencia;
		this.numerotarjeta = numerotarjeta;
		this.consecutivo = consecutivo;
		this.observacion = observacion;
		this.fecha = fecha;
	}

	public int getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}

	public String getNumerotarjeta() {
		return this.numerotarjeta;
	}

	public void setNumerotarjeta(String numerotarjeta) {
		this.numerotarjeta = numerotarjeta;
	}

	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
