package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario implements java.io.Serializable {

	private Date fecha;
	private short anio;
	private short mes;
	private short dia;
	private short trimestre;
	private short diaDeSemana;
	private short diaDeAnio;
	private short semanaDeAnio;

	public Calendario() {
	}

	public Calendario(Date fecha, short anio, short mes, short dia, short trimestre, short diaDeSemana, short diaDeAnio,
			short semanaDeAnio) {
		this.fecha = fecha;
		this.anio = anio;
		this.mes = mes;
		this.dia = dia;
		this.trimestre = trimestre;
		this.diaDeSemana = diaDeSemana;
		this.diaDeAnio = diaDeAnio;
		this.semanaDeAnio = semanaDeAnio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public short getAnio() {
		return this.anio;
	}

	public void setAnio(short anio) {
		this.anio = anio;
	}

	public short getMes() {
		return this.mes;
	}

	public void setMes(short mes) {
		this.mes = mes;
	}

	public short getDia() {
		return this.dia;
	}

	public void setDia(short dia) {
		this.dia = dia;
	}

	public short getTrimestre() {
		return this.trimestre;
	}

	public void setTrimestre(short trimestre) {
		this.trimestre = trimestre;
	}

	public short getDiaDeSemana() {
		return this.diaDeSemana;
	}

	public void setDiaDeSemana(short diaDeSemana) {
		this.diaDeSemana = diaDeSemana;
	}

	public short getDiaDeAnio() {
		return this.diaDeAnio;
	}

	public void setDiaDeAnio(short diaDeAnio) {
		this.diaDeAnio = diaDeAnio;
	}

	public short getSemanaDeAnio() {
		return this.semanaDeAnio;
	}

	public void setSemanaDeAnio(short semanaDeAnio) {
		this.semanaDeAnio = semanaDeAnio;
	}

}
