package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
public class Cargo implements java.io.Serializable {

	private String codcargo;
	private String nombrecargo;
	private Set personals = new HashSet(0);

	public Cargo() {
	}

	public Cargo(String codcargo) {
		this.codcargo = codcargo;
	}

	public Cargo(String codcargo, String nombrecargo, Set personals) {
		this.codcargo = codcargo;
		this.nombrecargo = nombrecargo;
		this.personals = personals;
	}

	public String getCodcargo() {
		return this.codcargo;
	}

	public void setCodcargo(String codcargo) {
		this.codcargo = codcargo;
	}

	public String getNombrecargo() {
		return this.nombrecargo;
	}

	public void setNombrecargo(String nombrecargo) {
		this.nombrecargo = nombrecargo;
	}

	public Set getPersonals() {
		return this.personals;
	}

	public void setPersonals(Set personals) {
		this.personals = personals;
	}

}
