package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Cita generated by hbm2java
 */
public class Cita implements java.io.Serializable {

	private CitaId id;
	private Activacion activacion;
	private String observacion;

	public Cita() {
	}

	public Cita(CitaId id, Activacion activacion) {
		this.id = id;
		this.activacion = activacion;
	}

	public Cita(CitaId id, Activacion activacion, String observacion) {
		this.id = id;
		this.activacion = activacion;
		this.observacion = observacion;
	}

	public CitaId getId() {
		return this.id;
	}

	public void setId(CitaId id) {
		this.id = id;
	}

	public Activacion getActivacion() {
		return this.activacion;
	}

	public void setActivacion(Activacion activacion) {
		this.activacion = activacion;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
