package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Cnedireccion generated by hbm2java
 */
public class Cnedireccion implements java.io.Serializable {

	private String codCentro;
	private String tipo;
	private String codEstado;
	private String codMunicipio;
	private String codParroquia;
	private String nombreCentro;
	private String direccionCentro;
	private String centroNuevo;

	public Cnedireccion() {
	}

	public Cnedireccion(String codCentro) {
		this.codCentro = codCentro;
	}

	public Cnedireccion(String codCentro, String tipo, String codEstado, String codMunicipio, String codParroquia,
			String nombreCentro, String direccionCentro, String centroNuevo) {
		this.codCentro = codCentro;
		this.tipo = tipo;
		this.codEstado = codEstado;
		this.codMunicipio = codMunicipio;
		this.codParroquia = codParroquia;
		this.nombreCentro = nombreCentro;
		this.direccionCentro = direccionCentro;
		this.centroNuevo = centroNuevo;
	}

	public String getCodCentro() {
		return this.codCentro;
	}

	public void setCodCentro(String codCentro) {
		this.codCentro = codCentro;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getCodEstado() {
		return this.codEstado;
	}

	public void setCodEstado(String codEstado) {
		this.codEstado = codEstado;
	}

	public String getCodMunicipio() {
		return this.codMunicipio;
	}

	public void setCodMunicipio(String codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public String getCodParroquia() {
		return this.codParroquia;
	}

	public void setCodParroquia(String codParroquia) {
		this.codParroquia = codParroquia;
	}

	public String getNombreCentro() {
		return this.nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	public String getDireccionCentro() {
		return this.direccionCentro;
	}

	public void setDireccionCentro(String direccionCentro) {
		this.direccionCentro = direccionCentro;
	}

	public String getCentroNuevo() {
		return this.centroNuevo;
	}

	public void setCentroNuevo(String centroNuevo) {
		this.centroNuevo = centroNuevo;
	}

}
