package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ComisionhistoricoId generated by hbm2java
 */
public class ComisionhistoricoId implements java.io.Serializable {

	private String documento;
	private Date fechainicio;

	public ComisionhistoricoId() {
	}

	public ComisionhistoricoId(String documento, Date fechainicio) {
		this.documento = documento;
		this.fechainicio = fechainicio;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComisionhistoricoId))
			return false;
		ComisionhistoricoId castOther = (ComisionhistoricoId) other;

		return ((this.getDocumento() == castOther.getDocumento()) || (this.getDocumento() != null
				&& castOther.getDocumento() != null && this.getDocumento().equals(castOther.getDocumento())))
				&& ((this.getFechainicio() == castOther.getFechainicio())
						|| (this.getFechainicio() != null && castOther.getFechainicio() != null
								&& this.getFechainicio().equals(castOther.getFechainicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37 * result + (getFechainicio() == null ? 0 : this.getFechainicio().hashCode());
		return result;
	}

}
