package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Comisionhistorico generated by hbm2java
 */
public class Comisionhistorico implements java.io.Serializable {

	private ComisionhistoricoId id;
	private Personal personal;
	private Date fechafin;
	private BigDecimal valor;

	public Comisionhistorico() {
	}

	public Comisionhistorico(ComisionhistoricoId id, Personal personal) {
		this.id = id;
		this.personal = personal;
	}

	public Comisionhistorico(ComisionhistoricoId id, Personal personal, Date fechafin, BigDecimal valor) {
		this.id = id;
		this.personal = personal;
		this.fechafin = fechafin;
		this.valor = valor;
	}

	public ComisionhistoricoId getId() {
		return this.id;
	}

	public void setId(ComisionhistoricoId id) {
		this.id = id;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

}
