package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Config generated by hbm2java
 */
public class Config implements java.io.Serializable {

	private Integer nautovoz;

	public Config() {
	}

	public Config(Integer nautovoz) {
		this.nautovoz = nautovoz;
	}

	public Integer getNautovoz() {
		return this.nautovoz;
	}

	public void setNautovoz(Integer nautovoz) {
		this.nautovoz = nautovoz;
	}

}
