package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private String numcuenta;
	private Banco banco;
	private String nombre;
	private BigDecimal saldo;
	private Set cuentacreditos = new HashSet(0);
	private Set depositostarjetas = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(String numcuenta, Banco banco) {
		this.numcuenta = numcuenta;
		this.banco = banco;
	}

	public Cuenta(String numcuenta, Banco banco, String nombre, BigDecimal saldo, Set cuentacreditos,
			Set depositostarjetas) {
		this.numcuenta = numcuenta;
		this.banco = banco;
		this.nombre = nombre;
		this.saldo = saldo;
		this.cuentacreditos = cuentacreditos;
		this.depositostarjetas = depositostarjetas;
	}

	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public Set getCuentacreditos() {
		return this.cuentacreditos;
	}

	public void setCuentacreditos(Set cuentacreditos) {
		this.cuentacreditos = cuentacreditos;
	}

	public Set getDepositostarjetas() {
		return this.depositostarjetas;
	}

	public void setDepositostarjetas(Set depositostarjetas) {
		this.depositostarjetas = depositostarjetas;
	}

}
