package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Cuentacredito generated by hbm2java
 */
public class Cuentacredito implements java.io.Serializable {

	private int consecutivo;
	private Cuenta cuenta;
	private Long valor;
	private Date fecha;
	private String usuario;
	private Date fechamod;
	private String usuariomod;
	private Byte tipo;
	private String observacion;

	public Cuentacredito() {
	}

	public Cuentacredito(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Cuentacredito(int consecutivo, Cuenta cuenta, Long valor, Date fecha, String usuario, Date fechamod,
			String usuariomod, Byte tipo, String observacion) {
		this.consecutivo = consecutivo;
		this.cuenta = cuenta;
		this.valor = valor;
		this.fecha = fecha;
		this.usuario = usuario;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
		this.tipo = tipo;
		this.observacion = observacion;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Byte getTipo() {
		return this.tipo;
	}

	public void setTipo(Byte tipo) {
		this.tipo = tipo;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
