package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * DeduccionesId generated by hbm2java
 */
public class DeduccionesId implements java.io.Serializable {

	private int consecutivo;
	private String descripcion;

	public DeduccionesId() {
	}

	public DeduccionesId(int consecutivo, String descripcion) {
		this.consecutivo = consecutivo;
		this.descripcion = descripcion;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeduccionesId))
			return false;
		DeduccionesId castOther = (DeduccionesId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getDescripcion() == castOther.getDescripcion())
						|| (this.getDescripcion() != null && castOther.getDescripcion() != null
								&& this.getDescripcion().equals(castOther.getDescripcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37 * result + (getDescripcion() == null ? 0 : this.getDescripcion().hashCode());
		return result;
	}

}
