package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Depositostarjeta generated by hbm2java
 */
public class Depositostarjeta implements java.io.Serializable {

	private int consecutivo;
	private Cuenta cuenta;
	private Tarjeta tarjeta;
	private Date fecha;
	private BigDecimal preciobolivar;
	private BigDecimal valordeposito;
	private String tipodebolivar;
	private BigDecimal depositopesos;
	private String tipodep;
	private Date fechamod;
	private String usuariomod;
	private String asesor;
	private String promotor;

	public Depositostarjeta() {
	}

	public Depositostarjeta(int consecutivo, Tarjeta tarjeta, Date fecha) {
		this.consecutivo = consecutivo;
		this.tarjeta = tarjeta;
		this.fecha = fecha;
	}

	public Depositostarjeta(int consecutivo, Cuenta cuenta, Tarjeta tarjeta, Date fecha, BigDecimal preciobolivar,
			BigDecimal valordeposito, String tipodebolivar, BigDecimal depositopesos, String tipodep, Date fechamod,
			String usuariomod, String asesor, String promotor) {
		this.consecutivo = consecutivo;
		this.cuenta = cuenta;
		this.tarjeta = tarjeta;
		this.fecha = fecha;
		this.preciobolivar = preciobolivar;
		this.valordeposito = valordeposito;
		this.tipodebolivar = tipodebolivar;
		this.depositopesos = depositopesos;
		this.tipodep = tipodep;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
		this.asesor = asesor;
		this.promotor = promotor;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	public BigDecimal getValordeposito() {
		return this.valordeposito;
	}

	public void setValordeposito(BigDecimal valordeposito) {
		this.valordeposito = valordeposito;
	}

	public String getTipodebolivar() {
		return this.tipodebolivar;
	}

	public void setTipodebolivar(String tipodebolivar) {
		this.tipodebolivar = tipodebolivar;
	}

	public BigDecimal getDepositopesos() {
		return this.depositopesos;
	}

	public void setDepositopesos(BigDecimal depositopesos) {
		this.depositopesos = depositopesos;
	}

	public String getTipodep() {
		return this.tipodep;
	}

	public void setTipodep(String tipodep) {
		this.tipodep = tipodep;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public String getAsesor() {
		return this.asesor;
	}

	public void setAsesor(String asesor) {
		this.asesor = asesor;
	}

	public String getPromotor() {
		return this.promotor;
	}

	public void setPromotor(String promotor) {
		this.promotor = promotor;
	}

}
