package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Diasemana generated by hbm2java
 */
public class Diasemana implements java.io.Serializable {

	private int codigodia;
	private String nombredia;

	public Diasemana() {
	}

	public Diasemana(int codigodia) {
		this.codigodia = codigodia;
	}

	public Diasemana(int codigodia, String nombredia) {
		this.codigodia = codigodia;
		this.nombredia = nombredia;
	}

	public int getCodigodia() {
		return this.codigodia;
	}

	public void setCodigodia(int codigodia) {
		this.codigodia = codigodia;
	}

	public String getNombredia() {
		return this.nombredia;
	}

	public void setNombredia(String nombredia) {
		this.nombredia = nombredia;
	}

}
