package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Dolartoday generated by hbm2java
 */
public class Dolartoday implements java.io.Serializable {

	private long epoch;
	private BigDecimal usdtransferencia;
	private BigDecimal usdefectivo;
	private BigDecimal usdpromedio;
	private BigDecimal usdpromedioreal;
	private BigDecimal usdsicad2;
	private BigDecimal usddolartoday;
	private BigDecimal eurtransferencia;
	private BigDecimal eurefectivo;
	private BigDecimal eurpromedio;
	private BigDecimal eurpromedioreal;
	private BigDecimal eurdolartoday;
	private BigDecimal bscolcompra;
	private BigDecimal bscolventa;
	private BigDecimal goldrate;
	private BigDecimal usdvefrate;
	private BigDecimal usdcolrate;
	private BigDecimal usdratetrm;
	private BigDecimal usdtrmfactor;
	private BigDecimal eurusdrate;
	private BigDecimal usdsicad1;
	private BigDecimal usdcencoex;

	public Dolartoday() {
	}

	public Dolartoday(long epoch) {
		this.epoch = epoch;
	}

	public Dolartoday(long epoch, BigDecimal usdtransferencia, BigDecimal usdefectivo, BigDecimal usdpromedio,
			BigDecimal usdpromedioreal, BigDecimal usdsicad2, BigDecimal usddolartoday, BigDecimal eurtransferencia,
			BigDecimal eurefectivo, BigDecimal eurpromedio, BigDecimal eurpromedioreal, BigDecimal eurdolartoday,
			BigDecimal bscolcompra, BigDecimal bscolventa, BigDecimal goldrate, BigDecimal usdvefrate,
			BigDecimal usdcolrate, BigDecimal usdratetrm, BigDecimal usdtrmfactor, BigDecimal eurusdrate,
			BigDecimal usdsicad1, BigDecimal usdcencoex) {
		this.epoch = epoch;
		this.usdtransferencia = usdtransferencia;
		this.usdefectivo = usdefectivo;
		this.usdpromedio = usdpromedio;
		this.usdpromedioreal = usdpromedioreal;
		this.usdsicad2 = usdsicad2;
		this.usddolartoday = usddolartoday;
		this.eurtransferencia = eurtransferencia;
		this.eurefectivo = eurefectivo;
		this.eurpromedio = eurpromedio;
		this.eurpromedioreal = eurpromedioreal;
		this.eurdolartoday = eurdolartoday;
		this.bscolcompra = bscolcompra;
		this.bscolventa = bscolventa;
		this.goldrate = goldrate;
		this.usdvefrate = usdvefrate;
		this.usdcolrate = usdcolrate;
		this.usdratetrm = usdratetrm;
		this.usdtrmfactor = usdtrmfactor;
		this.eurusdrate = eurusdrate;
		this.usdsicad1 = usdsicad1;
		this.usdcencoex = usdcencoex;
	}

	public long getEpoch() {
		return this.epoch;
	}

	public void setEpoch(long epoch) {
		this.epoch = epoch;
	}

	public BigDecimal getUsdtransferencia() {
		return this.usdtransferencia;
	}

	public void setUsdtransferencia(BigDecimal usdtransferencia) {
		this.usdtransferencia = usdtransferencia;
	}

	public BigDecimal getUsdefectivo() {
		return this.usdefectivo;
	}

	public void setUsdefectivo(BigDecimal usdefectivo) {
		this.usdefectivo = usdefectivo;
	}

	public BigDecimal getUsdpromedio() {
		return this.usdpromedio;
	}

	public void setUsdpromedio(BigDecimal usdpromedio) {
		this.usdpromedio = usdpromedio;
	}

	public BigDecimal getUsdpromedioreal() {
		return this.usdpromedioreal;
	}

	public void setUsdpromedioreal(BigDecimal usdpromedioreal) {
		this.usdpromedioreal = usdpromedioreal;
	}

	public BigDecimal getUsdsicad2() {
		return this.usdsicad2;
	}

	public void setUsdsicad2(BigDecimal usdsicad2) {
		this.usdsicad2 = usdsicad2;
	}

	public BigDecimal getUsddolartoday() {
		return this.usddolartoday;
	}

	public void setUsddolartoday(BigDecimal usddolartoday) {
		this.usddolartoday = usddolartoday;
	}

	public BigDecimal getEurtransferencia() {
		return this.eurtransferencia;
	}

	public void setEurtransferencia(BigDecimal eurtransferencia) {
		this.eurtransferencia = eurtransferencia;
	}

	public BigDecimal getEurefectivo() {
		return this.eurefectivo;
	}

	public void setEurefectivo(BigDecimal eurefectivo) {
		this.eurefectivo = eurefectivo;
	}

	public BigDecimal getEurpromedio() {
		return this.eurpromedio;
	}

	public void setEurpromedio(BigDecimal eurpromedio) {
		this.eurpromedio = eurpromedio;
	}

	public BigDecimal getEurpromedioreal() {
		return this.eurpromedioreal;
	}

	public void setEurpromedioreal(BigDecimal eurpromedioreal) {
		this.eurpromedioreal = eurpromedioreal;
	}

	public BigDecimal getEurdolartoday() {
		return this.eurdolartoday;
	}

	public void setEurdolartoday(BigDecimal eurdolartoday) {
		this.eurdolartoday = eurdolartoday;
	}

	public BigDecimal getBscolcompra() {
		return this.bscolcompra;
	}

	public void setBscolcompra(BigDecimal bscolcompra) {
		this.bscolcompra = bscolcompra;
	}

	public BigDecimal getBscolventa() {
		return this.bscolventa;
	}

	public void setBscolventa(BigDecimal bscolventa) {
		this.bscolventa = bscolventa;
	}

	public BigDecimal getGoldrate() {
		return this.goldrate;
	}

	public void setGoldrate(BigDecimal goldrate) {
		this.goldrate = goldrate;
	}

	public BigDecimal getUsdvefrate() {
		return this.usdvefrate;
	}

	public void setUsdvefrate(BigDecimal usdvefrate) {
		this.usdvefrate = usdvefrate;
	}

	public BigDecimal getUsdcolrate() {
		return this.usdcolrate;
	}

	public void setUsdcolrate(BigDecimal usdcolrate) {
		this.usdcolrate = usdcolrate;
	}

	public BigDecimal getUsdratetrm() {
		return this.usdratetrm;
	}

	public void setUsdratetrm(BigDecimal usdratetrm) {
		this.usdratetrm = usdratetrm;
	}

	public BigDecimal getUsdtrmfactor() {
		return this.usdtrmfactor;
	}

	public void setUsdtrmfactor(BigDecimal usdtrmfactor) {
		this.usdtrmfactor = usdtrmfactor;
	}

	public BigDecimal getEurusdrate() {
		return this.eurusdrate;
	}

	public void setEurusdrate(BigDecimal eurusdrate) {
		this.eurusdrate = eurusdrate;
	}

	public BigDecimal getUsdsicad1() {
		return this.usdsicad1;
	}

	public void setUsdsicad1(BigDecimal usdsicad1) {
		this.usdsicad1 = usdsicad1;
	}

	public BigDecimal getUsdcencoex() {
		return this.usdcencoex;
	}

	public void setUsdcencoex(BigDecimal usdcencoex) {
		this.usdcencoex = usdcencoex;
	}

}
