package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private String nit;
	private String nombrerazonsocial;
	private Set establecimientos = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String nit) {
		this.nit = nit;
	}

	public Empresa(String nit, String nombrerazonsocial, Set establecimientos) {
		this.nit = nit;
		this.nombrerazonsocial = nombrerazonsocial;
		this.establecimientos = establecimientos;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getNombrerazonsocial() {
		return this.nombrerazonsocial;
	}

	public void setNombrerazonsocial(String nombrerazonsocial) {
		this.nombrerazonsocial = nombrerazonsocial;
	}

	public Set getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set establecimientos) {
		this.establecimientos = establecimientos;
	}

}
