package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Envios generated by hbm2java
 */
public class Envios implements java.io.Serializable {

	private int consecutivo;
	private Asesor asesor;
	private Promotor promotor;
	private Date fecha;
	private String envia;
	private String recibe;
	private String oficina;
	private String ciudad;
	private String nrocupon;
	private Boolean enviado;
	private Boolean recibido;
	private Date fechaenvio;
	private Date fechamrw;

	public Envios() {
	}

	public Envios(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Envios(int consecutivo, Asesor asesor, Promotor promotor, Date fecha, String envia, String recibe,
			String oficina, String ciudad, String nrocupon, Boolean enviado, Boolean recibido, Date fechaenvio,
			Date fechamrw) {
		this.consecutivo = consecutivo;
		this.asesor = asesor;
		this.promotor = promotor;
		this.fecha = fecha;
		this.envia = envia;
		this.recibe = recibe;
		this.oficina = oficina;
		this.ciudad = ciudad;
		this.nrocupon = nrocupon;
		this.enviado = enviado;
		this.recibido = recibido;
		this.fechaenvio = fechaenvio;
		this.fechamrw = fechamrw;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Asesor getAsesor() {
		return this.asesor;
	}

	public void setAsesor(Asesor asesor) {
		this.asesor = asesor;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEnvia() {
		return this.envia;
	}

	public void setEnvia(String envia) {
		this.envia = envia;
	}

	public String getRecibe() {
		return this.recibe;
	}

	public void setRecibe(String recibe) {
		this.recibe = recibe;
	}

	public String getOficina() {
		return this.oficina;
	}

	public void setOficina(String oficina) {
		this.oficina = oficina;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getNrocupon() {
		return this.nrocupon;
	}

	public void setNrocupon(String nrocupon) {
		this.nrocupon = nrocupon;
	}

	public Boolean getEnviado() {
		return this.enviado;
	}

	public void setEnviado(Boolean enviado) {
		this.enviado = enviado;
	}

	public Boolean getRecibido() {
		return this.recibido;
	}

	public void setRecibido(Boolean recibido) {
		this.recibido = recibido;
	}

	public Date getFechaenvio() {
		return this.fechaenvio;
	}

	public void setFechaenvio(Date fechaenvio) {
		this.fechaenvio = fechaenvio;
	}

	public Date getFechamrw() {
		return this.fechamrw;
	}

	public void setFechamrw(Date fechamrw) {
		this.fechamrw = fechamrw;
	}

}
