package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Erroringresocadivi generated by hbm2java
 */
public class Erroringresocadivi implements java.io.Serializable {

	private ErroringresocadiviId id;
	private Activacion activacion;

	public Erroringresocadivi() {
	}

	public Erroringresocadivi(ErroringresocadiviId id, Activacion activacion) {
		this.id = id;
		this.activacion = activacion;
	}

	public ErroringresocadiviId getId() {
		return this.id;
	}

	public void setId(ErroringresocadiviId id) {
		this.id = id;
	}

	public Activacion getActivacion() {
		return this.activacion;
	}

	public void setActivacion(Activacion activacion) {
		this.activacion = activacion;
	}

}
