package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ErroringresocadiviId generated by hbm2java
 */
public class ErroringresocadiviId implements java.io.Serializable {

	private int consecutivo;
	private Date fecha;

	public ErroringresocadiviId() {
	}

	public ErroringresocadiviId(int consecutivo, Date fecha) {
		this.consecutivo = consecutivo;
		this.fecha = fecha;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ErroringresocadiviId))
			return false;
		ErroringresocadiviId castOther = (ErroringresocadiviId) other;

		return (this.getConsecutivo() == castOther.getConsecutivo())
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getConsecutivo();
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
