package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Estadoactivacion generated by hbm2java
 */
public class Estadoactivacion implements java.io.Serializable {

	private EstadoactivacionId id;
	private Actestado actestado;
	private Activacion activacion;
	private String observacion;

	public Estadoactivacion() {
	}

	public Estadoactivacion(EstadoactivacionId id, Actestado actestado, Activacion activacion) {
		this.id = id;
		this.actestado = actestado;
		this.activacion = activacion;
	}

	public Estadoactivacion(EstadoactivacionId id, Actestado actestado, Activacion activacion, String observacion) {
		this.id = id;
		this.actestado = actestado;
		this.activacion = activacion;
		this.observacion = observacion;
	}

	public EstadoactivacionId getId() {
		return this.id;
	}

	public void setId(EstadoactivacionId id) {
		this.id = id;
	}

	public Actestado getActestado() {
		return this.actestado;
	}

	public void setActestado(Actestado actestado) {
		this.actestado = actestado;
	}

	public Activacion getActivacion() {
		return this.activacion;
	}

	public void setActivacion(Activacion activacion) {
		this.activacion = activacion;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
