package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * EstablecimientoprecioId generated by hbm2java
 */
public class EstablecimientoprecioId implements java.io.Serializable {

	private String codigounico;
	private Date fechainicio;

	public EstablecimientoprecioId() {
	}

	public EstablecimientoprecioId(String codigounico, Date fechainicio) {
		this.codigounico = codigounico;
		this.fechainicio = fechainicio;
	}

	public String getCodigounico() {
		return this.codigounico;
	}

	public void setCodigounico(String codigounico) {
		this.codigounico = codigounico;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EstablecimientoprecioId))
			return false;
		EstablecimientoprecioId castOther = (EstablecimientoprecioId) other;

		return ((this.getCodigounico() == castOther.getCodigounico()) || (this.getCodigounico() != null
				&& castOther.getCodigounico() != null && this.getCodigounico().equals(castOther.getCodigounico())))
				&& ((this.getFechainicio() == castOther.getFechainicio())
						|| (this.getFechainicio() != null && castOther.getFechainicio() != null
								&& this.getFechainicio().equals(castOther.getFechainicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodigounico() == null ? 0 : this.getCodigounico().hashCode());
		result = 37 * result + (getFechainicio() == null ? 0 : this.getFechainicio().hashCode());
		return result;
	}

}
