package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Establecimientoprecio generated by hbm2java
 */
public class Establecimientoprecio implements java.io.Serializable {

	private EstablecimientoprecioId id;
	private Establecimiento establecimiento;
	private Date fechafin;
	private BigDecimal dolaroficina;
	private BigDecimal porcentajeoficina;
	private BigDecimal paridad;
	private BigDecimal paridadcliente;

	public Establecimientoprecio() {
	}

	public Establecimientoprecio(EstablecimientoprecioId id, Establecimiento establecimiento) {
		this.id = id;
		this.establecimiento = establecimiento;
	}

	public Establecimientoprecio(EstablecimientoprecioId id, Establecimiento establecimiento, Date fechafin,
			BigDecimal dolaroficina, BigDecimal porcentajeoficina, BigDecimal paridad, BigDecimal paridadcliente) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.fechafin = fechafin;
		this.dolaroficina = dolaroficina;
		this.porcentajeoficina = porcentajeoficina;
		this.paridad = paridad;
		this.paridadcliente = paridadcliente;
	}

	public EstablecimientoprecioId getId() {
		return this.id;
	}

	public void setId(EstablecimientoprecioId id) {
		this.id = id;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public BigDecimal getDolaroficina() {
		return this.dolaroficina;
	}

	public void setDolaroficina(BigDecimal dolaroficina) {
		this.dolaroficina = dolaroficina;
	}

	public BigDecimal getPorcentajeoficina() {
		return this.porcentajeoficina;
	}

	public void setPorcentajeoficina(BigDecimal porcentajeoficina) {
		this.porcentajeoficina = porcentajeoficina;
	}

	public BigDecimal getParidad() {
		return this.paridad;
	}

	public void setParidad(BigDecimal paridad) {
		this.paridad = paridad;
	}

	public BigDecimal getParidadcliente() {
		return this.paridadcliente;
	}

	public void setParidadcliente(BigDecimal paridadcliente) {
		this.paridadcliente = paridadcliente;
	}

}
