package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento implements java.io.Serializable {

	private String codigounico;
	private Bancocol bancocol;
	private Empresa empresa;
	private Pais pais;
	private String nombreestable;
	private String direccion;
	private String telefono;
	private BigDecimal porcentaje;
	private Boolean iva;
	private String numcuenta;
	private Boolean facturar;
	private Set tasadolarpromotorparametros = new HashSet(0);
	private Set porcentcomisiontxparampromos = new HashSet(0);
	private Set porcentajecomisiontxparams = new HashSet(0);
	private Set tasaeuropromotorparametros = new HashSet(0);
	private Set tasadolarparametros = new HashSet(0);
	private Set inventarios = new HashSet(0);
	private Set tasaeuroparametros = new HashSet(0);
	private Set establecimientoprecios = new HashSet(0);
	private Set puntoestablecimientos = new HashSet(0);
	private Set transaccions = new HashSet(0);
	private Set autovozs = new HashSet(0);
	private Set gravamenestablecimientos = new HashSet(0);

	public Establecimiento() {
	}

	public Establecimiento(String codigounico, String nombreestable) {
		this.codigounico = codigounico;
		this.nombreestable = nombreestable;
	}

	public Establecimiento(String codigounico, Bancocol bancocol, Empresa empresa, Pais pais, String nombreestable,
			String direccion, String telefono, BigDecimal porcentaje, Boolean iva, String numcuenta, Boolean facturar,
			Set tasadolarpromotorparametros, Set porcentcomisiontxparampromos, Set porcentajecomisiontxparams,
			Set tasaeuropromotorparametros, Set tasadolarparametros, Set inventarios, Set tasaeuroparametros,
			Set establecimientoprecios, Set puntoestablecimientos, Set transaccions, Set autovozs,
			Set gravamenestablecimientos) {
		this.codigounico = codigounico;
		this.bancocol = bancocol;
		this.empresa = empresa;
		this.pais = pais;
		this.nombreestable = nombreestable;
		this.direccion = direccion;
		this.telefono = telefono;
		this.porcentaje = porcentaje;
		this.iva = iva;
		this.numcuenta = numcuenta;
		this.facturar = facturar;
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
		this.tasadolarparametros = tasadolarparametros;
		this.inventarios = inventarios;
		this.tasaeuroparametros = tasaeuroparametros;
		this.establecimientoprecios = establecimientoprecios;
		this.puntoestablecimientos = puntoestablecimientos;
		this.transaccions = transaccions;
		this.autovozs = autovozs;
		this.gravamenestablecimientos = gravamenestablecimientos;
	}

	public String getCodigounico() {
		return this.codigounico;
	}

	public void setCodigounico(String codigounico) {
		this.codigounico = codigounico;
	}

	public Bancocol getBancocol() {
		return this.bancocol;
	}

	public void setBancocol(Bancocol bancocol) {
		this.bancocol = bancocol;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getNombreestable() {
		return this.nombreestable;
	}

	public void setNombreestable(String nombreestable) {
		this.nombreestable = nombreestable;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Boolean getIva() {
		return this.iva;
	}

	public void setIva(Boolean iva) {
		this.iva = iva;
	}

	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	public Boolean getFacturar() {
		return this.facturar;
	}

	public void setFacturar(Boolean facturar) {
		this.facturar = facturar;
	}

	public Set getTasadolarpromotorparametros() {
		return this.tasadolarpromotorparametros;
	}

	public void setTasadolarpromotorparametros(Set tasadolarpromotorparametros) {
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
	}

	public Set getPorcentcomisiontxparampromos() {
		return this.porcentcomisiontxparampromos;
	}

	public void setPorcentcomisiontxparampromos(Set porcentcomisiontxparampromos) {
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
	}

	public Set getPorcentajecomisiontxparams() {
		return this.porcentajecomisiontxparams;
	}

	public void setPorcentajecomisiontxparams(Set porcentajecomisiontxparams) {
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
	}

	public Set getTasaeuropromotorparametros() {
		return this.tasaeuropromotorparametros;
	}

	public void setTasaeuropromotorparametros(Set tasaeuropromotorparametros) {
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
	}

	public Set getTasadolarparametros() {
		return this.tasadolarparametros;
	}

	public void setTasadolarparametros(Set tasadolarparametros) {
		this.tasadolarparametros = tasadolarparametros;
	}

	public Set getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set inventarios) {
		this.inventarios = inventarios;
	}

	public Set getTasaeuroparametros() {
		return this.tasaeuroparametros;
	}

	public void setTasaeuroparametros(Set tasaeuroparametros) {
		this.tasaeuroparametros = tasaeuroparametros;
	}

	public Set getEstablecimientoprecios() {
		return this.establecimientoprecios;
	}

	public void setEstablecimientoprecios(Set establecimientoprecios) {
		this.establecimientoprecios = establecimientoprecios;
	}

	public Set getPuntoestablecimientos() {
		return this.puntoestablecimientos;
	}

	public void setPuntoestablecimientos(Set puntoestablecimientos) {
		this.puntoestablecimientos = puntoestablecimientos;
	}

	public Set getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set transaccions) {
		this.transaccions = transaccions;
	}

	public Set getAutovozs() {
		return this.autovozs;
	}

	public void setAutovozs(Set autovozs) {
		this.autovozs = autovozs;
	}

	public Set getGravamenestablecimientos() {
		return this.gravamenestablecimientos;
	}

	public void setGravamenestablecimientos(Set gravamenestablecimientos) {
		this.gravamenestablecimientos = gravamenestablecimientos;
	}

}
