package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	private FacturaId id;
	private Transaccion transaccion;
	private Set detallefacturas = new HashSet(0);

	public Factura() {
	}

	public Factura(FacturaId id) {
		this.id = id;
	}

	public Factura(FacturaId id, Transaccion transaccion, Set detallefacturas) {
		this.id = id;
		this.transaccion = transaccion;
		this.detallefacturas = detallefacturas;
	}

	public FacturaId getId() {
		return this.id;
	}

	public void setId(FacturaId id) {
		this.id = id;
	}

	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	public Set getDetallefacturas() {
		return this.detallefacturas;
	}

	public void setDetallefacturas(Set detallefacturas) {
		this.detallefacturas = detallefacturas;
	}

}
