package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * FranquiciaestablecimientoId generated by hbm2java
 */
public class FranquiciaestablecimientoId implements java.io.Serializable {

	private String establecimiento;
	private String franquicia;

	public FranquiciaestablecimientoId() {
	}

	public FranquiciaestablecimientoId(String establecimiento, String franquicia) {
		this.establecimiento = establecimiento;
		this.franquicia = franquicia;
	}

	public String getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(String establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(String franquicia) {
		this.franquicia = franquicia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FranquiciaestablecimientoId))
			return false;
		FranquiciaestablecimientoId castOther = (FranquiciaestablecimientoId) other;

		return ((this.getEstablecimiento() == castOther.getEstablecimiento())
				|| (this.getEstablecimiento() != null && castOther.getEstablecimiento() != null
						&& this.getEstablecimiento().equals(castOther.getEstablecimiento())))
				&& ((this.getFranquicia() == castOther.getFranquicia())
						|| (this.getFranquicia() != null && castOther.getFranquicia() != null
								&& this.getFranquicia().equals(castOther.getFranquicia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEstablecimiento() == null ? 0 : this.getEstablecimiento().hashCode());
		result = 37 * result + (getFranquicia() == null ? 0 : this.getFranquicia().hashCode());
		return result;
	}

}
