package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Franquiciaestablecimiento generated by hbm2java
 */
public class Franquiciaestablecimiento implements java.io.Serializable {

	private FranquiciaestablecimientoId id;
	private BigDecimal porcentaje;

	public Franquiciaestablecimiento() {
	}

	public Franquiciaestablecimiento(FranquiciaestablecimientoId id) {
		this.id = id;
	}

	public Franquiciaestablecimiento(FranquiciaestablecimientoId id, BigDecimal porcentaje) {
		this.id = id;
		this.porcentaje = porcentaje;
	}

	public FranquiciaestablecimientoId getId() {
		return this.id;
	}

	public void setId(FranquiciaestablecimientoId id) {
		this.id = id;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
