package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Gastos generated by hbm2java
 */
public class Gastos implements java.io.Serializable {

	private int consecutivo;
	private Personal personal;
	private Tipogasto tipogasto;
	private Date fecha;
	private Long valor;
	private String observacion;
	private BigDecimal valorbolivar;
	private Date fechamod;
	private String usuariomod;
	private Transferencia transferencia;

	public Gastos() {
	}

	public Gastos(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Gastos(int consecutivo, Personal personal, Tipogasto tipogasto, Date fecha, Long valor, String observacion,
			BigDecimal valorbolivar, Date fechamod, String usuariomod, Transferencia transferencia) {
		this.consecutivo = consecutivo;
		this.personal = personal;
		this.tipogasto = tipogasto;
		this.fecha = fecha;
		this.valor = valor;
		this.observacion = observacion;
		this.valorbolivar = valorbolivar;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
		this.transferencia = transferencia;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public Tipogasto getTipogasto() {
		return this.tipogasto;
	}

	public void setTipogasto(Tipogasto tipogasto) {
		this.tipogasto = tipogasto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public BigDecimal getValorbolivar() {
		return this.valorbolivar;
	}

	public void setValorbolivar(BigDecimal valorbolivar) {
		this.valorbolivar = valorbolivar;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Transferencia getTransferencia() {
		return this.transferencia;
	}

	public void setTransferencia(Transferencia transferencia) {
		this.transferencia = transferencia;
	}

}
