package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Gestor generated by hbm2java
 */
public class Gestor implements java.io.Serializable {

	private String documento;
	private Personal personal;
	private Set activagestors = new HashSet(0);
	private Set activacions = new HashSet(0);

	public Gestor() {
	}

	public Gestor(Personal personal) {
		this.personal = personal;
	}

	public Gestor(Personal personal, Set activagestors, Set activacions) {
		this.personal = personal;
		this.activagestors = activagestors;
		this.activacions = activacions;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public Set getActivagestors() {
		return this.activagestors;
	}

	public void setActivagestors(Set activagestors) {
		this.activagestors = activagestors;
	}

	public Set getActivacions() {
		return this.activacions;
	}

	public void setActivacions(Set activacions) {
		this.activacions = activacions;
	}

}
