package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventario generated by hbm2java
 */
public class Inventario implements java.io.Serializable {

	private InventarioId id;
	private Establecimiento establecimiento;
	private Producto producto;
	private BigDecimal valor;
	private BigDecimal cantidad;
	private Boolean activo;
	private Boolean prioridad;
	private Set detallefacturas = new HashSet(0);

	public Inventario() {
	}

	public Inventario(InventarioId id, Establecimiento establecimiento, Producto producto) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.producto = producto;
	}

	public Inventario(InventarioId id, Establecimiento establecimiento, Producto producto, BigDecimal valor,
			BigDecimal cantidad, Boolean activo, Boolean prioridad, Set detallefacturas) {
		this.id = id;
		this.establecimiento = establecimiento;
		this.producto = producto;
		this.valor = valor;
		this.cantidad = cantidad;
		this.activo = activo;
		this.prioridad = prioridad;
		this.detallefacturas = detallefacturas;
	}

	public InventarioId getId() {
		return this.id;
	}

	public void setId(InventarioId id) {
		this.id = id;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Boolean getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Boolean prioridad) {
		this.prioridad = prioridad;
	}

	public Set getDetallefacturas() {
		return this.detallefacturas;
	}

	public void setDetallefacturas(Set detallefacturas) {
		this.detallefacturas = detallefacturas;
	}

}
