package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Mesanio generated by hbm2java
 */
public class Mesanio implements java.io.Serializable {

	private int codigomes;
	private String nombremes;

	public Mesanio() {
	}

	public Mesanio(int codigomes) {
		this.codigomes = codigomes;
	}

	public Mesanio(int codigomes, String nombremes) {
		this.codigomes = codigomes;
		this.nombremes = nombremes;
	}

	public int getCodigomes() {
		return this.codigomes;
	}

	public void setCodigomes(int codigomes) {
		this.codigomes = codigomes;
	}

	public String getNombremes() {
		return this.nombremes;
	}

	public void setNombremes(String nombremes) {
		this.nombremes = nombremes;
	}

}
