package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Moneda generated by hbm2java
 */
public class Moneda implements java.io.Serializable {

	private String codigomoneda;
	private String nombreMoneda;
	private Set paridadmonedasForCodmonedadestino = new HashSet(0);
	private Set paridadmonedasForCodmonedaorigen = new HashSet(0);

	public Moneda() {
	}

	public Moneda(String codigomoneda) {
		this.codigomoneda = codigomoneda;
	}

	public Moneda(String codigomoneda, String nombreMoneda, Set paridadmonedasForCodmonedadestino,
			Set paridadmonedasForCodmonedaorigen) {
		this.codigomoneda = codigomoneda;
		this.nombreMoneda = nombreMoneda;
		this.paridadmonedasForCodmonedadestino = paridadmonedasForCodmonedadestino;
		this.paridadmonedasForCodmonedaorigen = paridadmonedasForCodmonedaorigen;
	}

	public String getCodigomoneda() {
		return this.codigomoneda;
	}

	public void setCodigomoneda(String codigomoneda) {
		this.codigomoneda = codigomoneda;
	}

	public String getNombreMoneda() {
		return this.nombreMoneda;
	}

	public void setNombreMoneda(String nombreMoneda) {
		this.nombreMoneda = nombreMoneda;
	}

	public Set getParidadmonedasForCodmonedadestino() {
		return this.paridadmonedasForCodmonedadestino;
	}

	public void setParidadmonedasForCodmonedadestino(Set paridadmonedasForCodmonedadestino) {
		this.paridadmonedasForCodmonedadestino = paridadmonedasForCodmonedadestino;
	}

	public Set getParidadmonedasForCodmonedaorigen() {
		return this.paridadmonedasForCodmonedaorigen;
	}

	public void setParidadmonedasForCodmonedaorigen(Set paridadmonedasForCodmonedaorigen) {
		this.paridadmonedasForCodmonedaorigen = paridadmonedasForCodmonedaorigen;
	}

}
