package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Operacion generated by hbm2java
 */
public class Operacion implements java.io.Serializable {

	private int codoperacion;
	private String descripcion;

	public Operacion() {
	}

	public Operacion(int codoperacion) {
		this.codoperacion = codoperacion;
	}

	public Operacion(int codoperacion, String descripcion) {
		this.codoperacion = codoperacion;
		this.descripcion = descripcion;
	}

	public int getCodoperacion() {
		return this.codoperacion;
	}

	public void setCodoperacion(int codoperacion) {
		this.codoperacion = codoperacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
