package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Paisiso generated by hbm2java
 */
public class Paisiso implements java.io.Serializable {

	private String codigopais;
	private String nombrepaisEs;
	private String nombrepaisEn;
	private String capital;
	private String nombrecompletoEn;
	private String codigopaisNumero;
	private String codigo31663Es;
	private String codigomoneda;
	private String nombreMoneda;
	private String pathBanderaRelativo;
	private String pathBanderaAbsoluta;
	private Boolean estado;
	private String pathBanderasExtracto;
	private String pathBanderaGui;
	private Set tasabolivartransferpaises = new HashSet(0);
	private Set paises = new HashSet(0);

	public Paisiso() {
	}

	public Paisiso(String codigopais) {
		this.codigopais = codigopais;
	}

	public Paisiso(String codigopais, String nombrepaisEs, String nombrepaisEn, String capital, String nombrecompletoEn,
			String codigopaisNumero, String codigo31663Es, String codigomoneda, String nombreMoneda,
			String pathBanderaRelativo, String pathBanderaAbsoluta, Boolean estado, String pathBanderasExtracto,
			String pathBanderaGui, Set tasabolivartransferpaises, Set paises) {
		this.codigopais = codigopais;
		this.nombrepaisEs = nombrepaisEs;
		this.nombrepaisEn = nombrepaisEn;
		this.capital = capital;
		this.nombrecompletoEn = nombrecompletoEn;
		this.codigopaisNumero = codigopaisNumero;
		this.codigo31663Es = codigo31663Es;
		this.codigomoneda = codigomoneda;
		this.nombreMoneda = nombreMoneda;
		this.pathBanderaRelativo = pathBanderaRelativo;
		this.pathBanderaAbsoluta = pathBanderaAbsoluta;
		this.estado = estado;
		this.pathBanderasExtracto = pathBanderasExtracto;
		this.pathBanderaGui = pathBanderaGui;
		this.tasabolivartransferpaises = tasabolivartransferpaises;
		this.paises = paises;
	}

	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	public String getNombrepaisEs() {
		return this.nombrepaisEs;
	}

	public void setNombrepaisEs(String nombrepaisEs) {
		this.nombrepaisEs = nombrepaisEs;
	}

	public String getNombrepaisEn() {
		return this.nombrepaisEn;
	}

	public void setNombrepaisEn(String nombrepaisEn) {
		this.nombrepaisEn = nombrepaisEn;
	}

	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	public String getNombrecompletoEn() {
		return this.nombrecompletoEn;
	}

	public void setNombrecompletoEn(String nombrecompletoEn) {
		this.nombrecompletoEn = nombrecompletoEn;
	}

	public String getCodigopaisNumero() {
		return this.codigopaisNumero;
	}

	public void setCodigopaisNumero(String codigopaisNumero) {
		this.codigopaisNumero = codigopaisNumero;
	}

	public String getCodigo31663Es() {
		return this.codigo31663Es;
	}

	public void setCodigo31663Es(String codigo31663Es) {
		this.codigo31663Es = codigo31663Es;
	}

	public String getCodigomoneda() {
		return this.codigomoneda;
	}

	public void setCodigomoneda(String codigomoneda) {
		this.codigomoneda = codigomoneda;
	}

	public String getNombreMoneda() {
		return this.nombreMoneda;
	}

	public void setNombreMoneda(String nombreMoneda) {
		this.nombreMoneda = nombreMoneda;
	}

	public String getPathBanderaRelativo() {
		return this.pathBanderaRelativo;
	}

	public void setPathBanderaRelativo(String pathBanderaRelativo) {
		this.pathBanderaRelativo = pathBanderaRelativo;
	}

	public String getPathBanderaAbsoluta() {
		return this.pathBanderaAbsoluta;
	}

	public void setPathBanderaAbsoluta(String pathBanderaAbsoluta) {
		this.pathBanderaAbsoluta = pathBanderaAbsoluta;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public String getPathBanderasExtracto() {
		return this.pathBanderasExtracto;
	}

	public void setPathBanderasExtracto(String pathBanderasExtracto) {
		this.pathBanderasExtracto = pathBanderasExtracto;
	}

	public String getPathBanderaGui() {
		return this.pathBanderaGui;
	}

	public void setPathBanderaGui(String pathBanderaGui) {
		this.pathBanderaGui = pathBanderaGui;
	}

	public Set getTasabolivartransferpaises() {
		return this.tasabolivartransferpaises;
	}

	public void setTasabolivartransferpaises(Set tasabolivartransferpaises) {
		this.tasabolivartransferpaises = tasabolivartransferpaises;
	}

	public Set getPaises() {
		return this.paises;
	}

	public void setPaises(Set paises) {
		this.paises = paises;
	}

}
