package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private String codigopais;
	private Paisiso paisiso;
	private String nombre;
	private Boolean estado;
	private Set tasaeuroparametros = new HashSet(0);
	private Set promotorcomisiontxes = new HashSet(0);
	private Set promotortasas = new HashSet(0);
	private Set tasaeuropromotorparametros = new HashSet(0);
	private Set porcentajecomisiontxes = new HashSet(0);
	private Set porcentcomisiontxparampromos = new HashSet(0);
	private Set tasadolarparametros = new HashSet(0);
	private Set establecimientos = new HashSet(0);
	private Set tasadolarpromotorparametros = new HashSet(0);
	private Set porcentajecomisiontxparams = new HashSet(0);
	private Set tasadolars = new HashSet(0);

	public Pais() {
	}

	public Pais(String codigopais) {
		this.codigopais = codigopais;
	}

	public Pais(String codigopais, Paisiso paisiso, String nombre, Boolean estado, Set tasaeuroparametros,
			Set promotorcomisiontxes, Set promotortasas, Set tasaeuropromotorparametros, Set porcentajecomisiontxes,
			Set porcentcomisiontxparampromos, Set tasadolarparametros, Set establecimientos,
			Set tasadolarpromotorparametros, Set porcentajecomisiontxparams, Set tasadolars) {
		this.codigopais = codigopais;
		this.paisiso = paisiso;
		this.nombre = nombre;
		this.estado = estado;
		this.tasaeuroparametros = tasaeuroparametros;
		this.promotorcomisiontxes = promotorcomisiontxes;
		this.promotortasas = promotortasas;
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
		this.porcentajecomisiontxes = porcentajecomisiontxes;
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
		this.tasadolarparametros = tasadolarparametros;
		this.establecimientos = establecimientos;
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
		this.tasadolars = tasadolars;
	}

	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	public Paisiso getPaisiso() {
		return this.paisiso;
	}

	public void setPaisiso(Paisiso paisiso) {
		this.paisiso = paisiso;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set getTasaeuroparametros() {
		return this.tasaeuroparametros;
	}

	public void setTasaeuroparametros(Set tasaeuroparametros) {
		this.tasaeuroparametros = tasaeuroparametros;
	}

	public Set getPromotorcomisiontxes() {
		return this.promotorcomisiontxes;
	}

	public void setPromotorcomisiontxes(Set promotorcomisiontxes) {
		this.promotorcomisiontxes = promotorcomisiontxes;
	}

	public Set getPromotortasas() {
		return this.promotortasas;
	}

	public void setPromotortasas(Set promotortasas) {
		this.promotortasas = promotortasas;
	}

	public Set getTasaeuropromotorparametros() {
		return this.tasaeuropromotorparametros;
	}

	public void setTasaeuropromotorparametros(Set tasaeuropromotorparametros) {
		this.tasaeuropromotorparametros = tasaeuropromotorparametros;
	}

	public Set getPorcentajecomisiontxes() {
		return this.porcentajecomisiontxes;
	}

	public void setPorcentajecomisiontxes(Set porcentajecomisiontxes) {
		this.porcentajecomisiontxes = porcentajecomisiontxes;
	}

	public Set getPorcentcomisiontxparampromos() {
		return this.porcentcomisiontxparampromos;
	}

	public void setPorcentcomisiontxparampromos(Set porcentcomisiontxparampromos) {
		this.porcentcomisiontxparampromos = porcentcomisiontxparampromos;
	}

	public Set getTasadolarparametros() {
		return this.tasadolarparametros;
	}

	public void setTasadolarparametros(Set tasadolarparametros) {
		this.tasadolarparametros = tasadolarparametros;
	}

	public Set getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set establecimientos) {
		this.establecimientos = establecimientos;
	}

	public Set getTasadolarpromotorparametros() {
		return this.tasadolarpromotorparametros;
	}

	public void setTasadolarpromotorparametros(Set tasadolarpromotorparametros) {
		this.tasadolarpromotorparametros = tasadolarpromotorparametros;
	}

	public Set getPorcentajecomisiontxparams() {
		return this.porcentajecomisiontxparams;
	}

	public void setPorcentajecomisiontxparams(Set porcentajecomisiontxparams) {
		this.porcentajecomisiontxparams = porcentajecomisiontxparams;
	}

	public Set getTasadolars() {
		return this.tasadolars;
	}

	public void setTasadolars(Set tasadolars) {
		this.tasadolars = tasadolars;
	}

}
