package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Paridadmoneda generated by hbm2java
 */
public class Paridadmoneda implements java.io.Serializable {

	private Date fecha;
	private Moneda monedaByCodmonedadestino;
	private Moneda monedaByCodmonedaorigen;
	private BigDecimal paridad;

	public Paridadmoneda() {
	}

	public Paridadmoneda(Date fecha) {
		this.fecha = fecha;
	}

	public Paridadmoneda(Date fecha, Moneda monedaByCodmonedadestino, Moneda monedaByCodmonedaorigen,
			BigDecimal paridad) {
		this.fecha = fecha;
		this.monedaByCodmonedadestino = monedaByCodmonedadestino;
		this.monedaByCodmonedaorigen = monedaByCodmonedaorigen;
		this.paridad = paridad;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Moneda getMonedaByCodmonedadestino() {
		return this.monedaByCodmonedadestino;
	}

	public void setMonedaByCodmonedadestino(Moneda monedaByCodmonedadestino) {
		this.monedaByCodmonedadestino = monedaByCodmonedadestino;
	}

	public Moneda getMonedaByCodmonedaorigen() {
		return this.monedaByCodmonedaorigen;
	}

	public void setMonedaByCodmonedaorigen(Moneda monedaByCodmonedaorigen) {
		this.monedaByCodmonedaorigen = monedaByCodmonedaorigen;
	}

	public BigDecimal getParidad() {
		return this.paridad;
	}

	public void setParidad(BigDecimal paridad) {
		this.paridad = paridad;
	}

}
