package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Personaltipoproceso generated by hbm2java
 */
public class Personaltipoproceso implements java.io.Serializable {

	private PersonaltipoprocesoId id;
	private Date fechafin;
	private BigDecimal porcentaje;

	public Personaltipoproceso() {
	}

	public Personaltipoproceso(PersonaltipoprocesoId id) {
		this.id = id;
	}

	public Personaltipoproceso(PersonaltipoprocesoId id, Date fechafin, BigDecimal porcentaje) {
		this.id = id;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	public PersonaltipoprocesoId getId() {
		return this.id;
	}

	public void setId(PersonaltipoprocesoId id) {
		this.id = id;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
