package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PersonaltipoprocesoId generated by hbm2java
 */
public class PersonaltipoprocesoId implements java.io.Serializable {

	private String documento;
	private Date fechainicio;
	private String puntodeventa;
	private String tipoproceso;

	public PersonaltipoprocesoId() {
	}

	public PersonaltipoprocesoId(String documento, Date fechainicio, String puntodeventa, String tipoproceso) {
		this.documento = documento;
		this.fechainicio = fechainicio;
		this.puntodeventa = puntodeventa;
		this.tipoproceso = tipoproceso;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public String getPuntodeventa() {
		return this.puntodeventa;
	}

	public void setPuntodeventa(String puntodeventa) {
		this.puntodeventa = puntodeventa;
	}

	public String getTipoproceso() {
		return this.tipoproceso;
	}

	public void setTipoproceso(String tipoproceso) {
		this.tipoproceso = tipoproceso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonaltipoprocesoId))
			return false;
		PersonaltipoprocesoId castOther = (PersonaltipoprocesoId) other;

		return ((this.getDocumento() == castOther.getDocumento()) || (this.getDocumento() != null
				&& castOther.getDocumento() != null && this.getDocumento().equals(castOther.getDocumento())))
				&& ((this.getFechainicio() == castOther.getFechainicio())
						|| (this.getFechainicio() != null && castOther.getFechainicio() != null
								&& this.getFechainicio().equals(castOther.getFechainicio())))
				&& ((this.getPuntodeventa() == castOther.getPuntodeventa())
						|| (this.getPuntodeventa() != null && castOther.getPuntodeventa() != null
								&& this.getPuntodeventa().equals(castOther.getPuntodeventa())))
				&& ((this.getTipoproceso() == castOther.getTipoproceso())
						|| (this.getTipoproceso() != null && castOther.getTipoproceso() != null
								&& this.getTipoproceso().equals(castOther.getTipoproceso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		result = 37 * result + (getFechainicio() == null ? 0 : this.getFechainicio().hashCode());
		result = 37 * result + (getPuntodeventa() == null ? 0 : this.getPuntodeventa().hashCode());
		result = 37 * result + (getTipoproceso() == null ? 0 : this.getTipoproceso().hashCode());
		return result;
	}

}
