package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PorcentajeparametrosId generated by hbm2java
 */
public class PorcentajeparametrosId implements java.io.Serializable {

	private String codbanco;
	private String codfranquicia;
	private String codpais;
	private Date fechainicio;

	public PorcentajeparametrosId() {
	}

	public PorcentajeparametrosId(String codbanco, String codfranquicia, String codpais, Date fechainicio) {
		this.codbanco = codbanco;
		this.codfranquicia = codfranquicia;
		this.codpais = codpais;
		this.fechainicio = fechainicio;
	}

	public String getCodbanco() {
		return this.codbanco;
	}

	public void setCodbanco(String codbanco) {
		this.codbanco = codbanco;
	}

	public String getCodfranquicia() {
		return this.codfranquicia;
	}

	public void setCodfranquicia(String codfranquicia) {
		this.codfranquicia = codfranquicia;
	}

	public String getCodpais() {
		return this.codpais;
	}

	public void setCodpais(String codpais) {
		this.codpais = codpais;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PorcentajeparametrosId))
			return false;
		PorcentajeparametrosId castOther = (PorcentajeparametrosId) other;

		return ((this.getCodbanco() == castOther.getCodbanco()) || (this.getCodbanco() != null
				&& castOther.getCodbanco() != null && this.getCodbanco().equals(castOther.getCodbanco())))
				&& ((this.getCodfranquicia() == castOther.getCodfranquicia())
						|| (this.getCodfranquicia() != null && castOther.getCodfranquicia() != null
								&& this.getCodfranquicia().equals(castOther.getCodfranquicia())))
				&& ((this.getCodpais() == castOther.getCodpais()) || (this.getCodpais() != null
						&& castOther.getCodpais() != null && this.getCodpais().equals(castOther.getCodpais())))
				&& ((this.getFechainicio() == castOther.getFechainicio())
						|| (this.getFechainicio() != null && castOther.getFechainicio() != null
								&& this.getFechainicio().equals(castOther.getFechainicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodbanco() == null ? 0 : this.getCodbanco().hashCode());
		result = 37 * result + (getCodfranquicia() == null ? 0 : this.getCodfranquicia().hashCode());
		result = 37 * result + (getCodpais() == null ? 0 : this.getCodpais().hashCode());
		result = 37 * result + (getFechainicio() == null ? 0 : this.getFechainicio().hashCode());
		return result;
	}

}
