package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Porcentajecomisiontxparam generated by hbm2java
 */
public class Porcentajecomisiontxparam implements java.io.Serializable {

	private int consecutivo;
	private Banco banco;
	private Establecimiento establecimiento;
	private Franquicia franquicia;
	private Pais pais;
	private String tipocupo;
	private BigDecimal porcentaje;
	private BigDecimal porcentajeTac;
	private Date fechainicio;
	private Date fechafin;

	public Porcentajecomisiontxparam() {
	}

	public Porcentajecomisiontxparam(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Porcentajecomisiontxparam(int consecutivo, Banco banco, Establecimiento establecimiento,
			Franquicia franquicia, Pais pais, String tipocupo, BigDecimal porcentaje, BigDecimal porcentajeTac,
			Date fechainicio, Date fechafin) {
		this.consecutivo = consecutivo;
		this.banco = banco;
		this.establecimiento = establecimiento;
		this.franquicia = franquicia;
		this.pais = pais;
		this.tipocupo = tipocupo;
		this.porcentaje = porcentaje;
		this.porcentajeTac = porcentajeTac;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public Franquicia getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(Franquicia franquicia) {
		this.franquicia = franquicia;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getTipocupo() {
		return this.tipocupo;
	}

	public void setTipocupo(String tipocupo) {
		this.tipocupo = tipocupo;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public BigDecimal getPorcentajeTac() {
		return this.porcentajeTac;
	}

	public void setPorcentajeTac(BigDecimal porcentajeTac) {
		this.porcentajeTac = porcentajeTac;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
