package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Porcentajecomisiontx generated by hbm2java
 */
public class Porcentajecomisiontx implements java.io.Serializable {

	private PorcentajecomisiontxId id;
	private Pais pais;
	private Date fechafin;
	private BigDecimal porcentaje;

	public Porcentajecomisiontx() {
	}

	public Porcentajecomisiontx(PorcentajecomisiontxId id, Pais pais) {
		this.id = id;
		this.pais = pais;
	}

	public Porcentajecomisiontx(PorcentajecomisiontxId id, Pais pais, Date fechafin, BigDecimal porcentaje) {
		this.id = id;
		this.pais = pais;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	public PorcentajecomisiontxId getId() {
		return this.id;
	}

	public void setId(PorcentajecomisiontxId id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
