package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * PorcentajecomisiontxId generated by hbm2java
 */
public class PorcentajecomisiontxId implements java.io.Serializable {

	private String codpais;
	private Date fechainicio;

	public PorcentajecomisiontxId() {
	}

	public PorcentajecomisiontxId(String codpais, Date fechainicio) {
		this.codpais = codpais;
		this.fechainicio = fechainicio;
	}

	public String getCodpais() {
		return this.codpais;
	}

	public void setCodpais(String codpais) {
		this.codpais = codpais;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PorcentajecomisiontxId))
			return false;
		PorcentajecomisiontxId castOther = (PorcentajecomisiontxId) other;

		return ((this.getCodpais() == castOther.getCodpais()) || (this.getCodpais() != null
				&& castOther.getCodpais() != null && this.getCodpais().equals(castOther.getCodpais())))
				&& ((this.getFechainicio() == castOther.getFechainicio())
						|| (this.getFechainicio() != null && castOther.getFechainicio() != null
								&& this.getFechainicio().equals(castOther.getFechainicio())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodpais() == null ? 0 : this.getCodpais().hashCode());
		result = 37 * result + (getFechainicio() == null ? 0 : this.getFechainicio().hashCode());
		return result;
	}

}
