package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Porcentajeparametros generated by hbm2java
 */
public class Porcentajeparametros implements java.io.Serializable {

	private PorcentajeparametrosId id;
	private Date fechafin;
	private Short porcentaje;

	public Porcentajeparametros() {
	}

	public Porcentajeparametros(PorcentajeparametrosId id) {
		this.id = id;
	}

	public Porcentajeparametros(PorcentajeparametrosId id, Date fechafin, Short porcentaje) {
		this.id = id;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	public PorcentajeparametrosId getId() {
		return this.id;
	}

	public void setId(PorcentajeparametrosId id) {
		this.id = id;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public Short getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Short porcentaje) {
		this.porcentaje = porcentaje;
	}

}
