package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Porcentajeparametrospromotor generated by hbm2java
 */
public class Porcentajeparametrospromotor implements java.io.Serializable {

	private PorcentajeparametrospromotorId id;
	private Date fechafin;
	private Short porcentaje;

	public Porcentajeparametrospromotor() {
	}

	public Porcentajeparametrospromotor(PorcentajeparametrospromotorId id) {
		this.id = id;
	}

	public Porcentajeparametrospromotor(PorcentajeparametrospromotorId id, Date fechafin, Short porcentaje) {
		this.id = id;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	public PorcentajeparametrospromotorId getId() {
		return this.id;
	}

	public void setId(PorcentajeparametrospromotorId id) {
		this.id = id;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public Short getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Short porcentaje) {
		this.porcentaje = porcentaje;
	}

}
