package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private String refproducto;
	private String nombreproducto;
	private String marca;
	private Integer valorminimo;
	private Integer valormaximo;
	private Short cantminimo;
	private Short cantmaximo;
	private Short porcentaje;
	private Set inventarios = new HashSet(0);

	public Producto() {
	}

	public Producto(String refproducto) {
		this.refproducto = refproducto;
	}

	public Producto(String refproducto, String nombreproducto, String marca, Integer valorminimo, Integer valormaximo,
			Short cantminimo, Short cantmaximo, Short porcentaje, Set inventarios) {
		this.refproducto = refproducto;
		this.nombreproducto = nombreproducto;
		this.marca = marca;
		this.valorminimo = valorminimo;
		this.valormaximo = valormaximo;
		this.cantminimo = cantminimo;
		this.cantmaximo = cantmaximo;
		this.porcentaje = porcentaje;
		this.inventarios = inventarios;
	}

	public String getRefproducto() {
		return this.refproducto;
	}

	public void setRefproducto(String refproducto) {
		this.refproducto = refproducto;
	}

	public String getNombreproducto() {
		return this.nombreproducto;
	}

	public void setNombreproducto(String nombreproducto) {
		this.nombreproducto = nombreproducto;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public Integer getValorminimo() {
		return this.valorminimo;
	}

	public void setValorminimo(Integer valorminimo) {
		this.valorminimo = valorminimo;
	}

	public Integer getValormaximo() {
		return this.valormaximo;
	}

	public void setValormaximo(Integer valormaximo) {
		this.valormaximo = valormaximo;
	}

	public Short getCantminimo() {
		return this.cantminimo;
	}

	public void setCantminimo(Short cantminimo) {
		this.cantminimo = cantminimo;
	}

	public Short getCantmaximo() {
		return this.cantmaximo;
	}

	public void setCantmaximo(Short cantmaximo) {
		this.cantmaximo = cantmaximo;
	}

	public Short getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Short porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Set getInventarios() {
		return this.inventarios;
	}

	public void setInventarios(Set inventarios) {
		this.inventarios = inventarios;
	}

}
