package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * PromotorfranquiciaId generated by hbm2java
 */
public class PromotorfranquiciaId implements java.io.Serializable {

	private String codfranquicia;
	private String documento;

	public PromotorfranquiciaId() {
	}

	public PromotorfranquiciaId(String codfranquicia, String documento) {
		this.codfranquicia = codfranquicia;
		this.documento = documento;
	}

	public String getCodfranquicia() {
		return this.codfranquicia;
	}

	public void setCodfranquicia(String codfranquicia) {
		this.codfranquicia = codfranquicia;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PromotorfranquiciaId))
			return false;
		PromotorfranquiciaId castOther = (PromotorfranquiciaId) other;

		return ((this.getCodfranquicia() == castOther.getCodfranquicia())
				|| (this.getCodfranquicia() != null && castOther.getCodfranquicia() != null
						&& this.getCodfranquicia().equals(castOther.getCodfranquicia())))
				&& ((this.getDocumento() == castOther.getDocumento()) || (this.getDocumento() != null
						&& castOther.getDocumento() != null && this.getDocumento().equals(castOther.getDocumento())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodfranquicia() == null ? 0 : this.getCodfranquicia().hashCode());
		result = 37 * result + (getDocumento() == null ? 0 : this.getDocumento().hashCode());
		return result;
	}

}
