package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Promotorcomisiontx generated by hbm2java
 */
public class Promotorcomisiontx implements java.io.Serializable {

	private PromotorcomisiontxId id;
	private Pais pais;
	private Promotor promotor;
	private Date fechafin;
	private BigDecimal porcentaje;

	public Promotorcomisiontx() {
	}

	public Promotorcomisiontx(PromotorcomisiontxId id, Pais pais, Promotor promotor) {
		this.id = id;
		this.pais = pais;
		this.promotor = promotor;
	}

	public Promotorcomisiontx(PromotorcomisiontxId id, Pais pais, Promotor promotor, Date fechafin,
			BigDecimal porcentaje) {
		this.id = id;
		this.pais = pais;
		this.promotor = promotor;
		this.fechafin = fechafin;
		this.porcentaje = porcentaje;
	}

	public PromotorcomisiontxId getId() {
		return this.id;
	}

	public void setId(PromotorcomisiontxId id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
