package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Promotortasa generated by hbm2java
 */
public class Promotortasa implements java.io.Serializable {

	private PromotortasaId id;
	private Pais pais;
	private Promotor promotor;
	private BigDecimal tasa;
	private BigDecimal tasadolar;
	private Date fechafin;

	public Promotortasa() {
	}

	public Promotortasa(PromotortasaId id, Pais pais, Promotor promotor) {
		this.id = id;
		this.pais = pais;
		this.promotor = promotor;
	}

	public Promotortasa(PromotortasaId id, Pais pais, Promotor promotor, BigDecimal tasa, BigDecimal tasadolar,
			Date fechafin) {
		this.id = id;
		this.pais = pais;
		this.promotor = promotor;
		this.tasa = tasa;
		this.tasadolar = tasadolar;
		this.fechafin = fechafin;
	}

	public PromotortasaId getId() {
		return this.id;
	}

	public void setId(PromotortasaId id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public BigDecimal getTasadolar() {
		return this.tasadolar;
	}

	public void setTasadolar(BigDecimal tasadolar) {
		this.tasadolar = tasadolar;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
