package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Puntodeventa generated by hbm2java
 */
public class Puntodeventa implements java.io.Serializable {

	private String codpuntoventa;
	private String nombre;
	private Set puntoestablecimientos = new HashSet(0);

	public Puntodeventa() {
	}

	public Puntodeventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	public Puntodeventa(String codpuntoventa, String nombre, Set puntoestablecimientos) {
		this.codpuntoventa = codpuntoventa;
		this.nombre = nombre;
		this.puntoestablecimientos = puntoestablecimientos;
	}

	public String getCodpuntoventa() {
		return this.codpuntoventa;
	}

	public void setCodpuntoventa(String codpuntoventa) {
		this.codpuntoventa = codpuntoventa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPuntoestablecimientos() {
		return this.puntoestablecimientos;
	}

	public void setPuntoestablecimientos(Set puntoestablecimientos) {
		this.puntoestablecimientos = puntoestablecimientos;
	}

}
