package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Reportes generated by hbm2java
 */
public class Reportes implements java.io.Serializable {

	private String codreporte;
	private String nombrereporte;
	private Short parametros;
	private String descripcion;

	public Reportes() {
	}

	public Reportes(String codreporte) {
		this.codreporte = codreporte;
	}

	public Reportes(String codreporte, String nombrereporte, Short parametros, String descripcion) {
		this.codreporte = codreporte;
		this.nombrereporte = nombrereporte;
		this.parametros = parametros;
		this.descripcion = descripcion;
	}

	public String getCodreporte() {
		return this.codreporte;
	}

	public void setCodreporte(String codreporte) {
		this.codreporte = codreporte;
	}

	public String getNombrereporte() {
		return this.nombrereporte;
	}

	public void setNombrereporte(String nombrereporte) {
		this.nombrereporte = nombrereporte;
	}

	public Short getParametros() {
		return this.parametros;
	}

	public void setParametros(Short parametros) {
		this.parametros = parametros;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
