package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Saldodiariopromotor generated by hbm2java
 */
public class Saldodiariopromotor implements java.io.Serializable {

	private SaldodiariopromotorId id;
	private Promotor promotor;
	private BigDecimal saldo;
	private Date fechamod;
	private String usuariomod;

	public Saldodiariopromotor() {
	}

	public Saldodiariopromotor(SaldodiariopromotorId id, Promotor promotor) {
		this.id = id;
		this.promotor = promotor;
	}

	public Saldodiariopromotor(SaldodiariopromotorId id, Promotor promotor, BigDecimal saldo, Date fechamod,
			String usuariomod) {
		this.id = id;
		this.promotor = promotor;
		this.saldo = saldo;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
	}

	public SaldodiariopromotorId getId() {
		return this.id;
	}

	public void setId(SaldodiariopromotorId id) {
		this.id = id;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

}
