package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Saldo generated by hbm2java
 */
public class Saldo implements java.io.Serializable {

	private SaldoId id;
	private Personal personal;
	private BigDecimal saldo;
	private String usuariomod;
	private Date fechamod;

	public Saldo() {
	}

	public Saldo(SaldoId id, Personal personal) {
		this.id = id;
		this.personal = personal;
	}

	public Saldo(SaldoId id, Personal personal, BigDecimal saldo, String usuariomod, Date fechamod) {
		this.id = id;
		this.personal = personal;
		this.saldo = saldo;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	public SaldoId getId() {
		return this.id;
	}

	public void setId(SaldoId id) {
		this.id = id;
	}

	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
