package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Saldodepositos generated by hbm2java
 */
public class Saldodepositos implements java.io.Serializable {

	private SaldodepositosId id;
	private Tarjeta tarjeta;
	private BigDecimal saldo;
	private String usuariomod;
	private Date fechamod;

	public Saldodepositos() {
	}

	public Saldodepositos(SaldodepositosId id, Tarjeta tarjeta) {
		this.id = id;
		this.tarjeta = tarjeta;
	}

	public Saldodepositos(SaldodepositosId id, Tarjeta tarjeta, BigDecimal saldo, String usuariomod, Date fechamod) {
		this.id = id;
		this.tarjeta = tarjeta;
		this.saldo = saldo;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	public SaldodepositosId getId() {
		return this.id;
	}

	public void setId(SaldodepositosId id) {
		this.id = id;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public BigDecimal getSaldo() {
		return this.saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
