package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Sales generated by hbm2java
 */
public class Sales implements java.io.Serializable {

	private SalesId id;

	public Sales() {
	}

	public Sales(SalesId id) {
		this.id = id;
	}

	public SalesId getId() {
		return this.id;
	}

	public void setId(SalesId id) {
		this.id = id;
	}

}
