package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Solicitudtransferencia generated by hbm2java
 */
public class Solicitudtransferencia implements java.io.Serializable {

	private int consecutivo;
	private Integer depositos;
	private String documento;
	private Date fecha;
	private Integer saldoanterior;
	private Integer valor;

	public Solicitudtransferencia() {
	}

	public Solicitudtransferencia(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Solicitudtransferencia(int consecutivo, Integer depositos, String documento, Date fecha,
			Integer saldoanterior, Integer valor) {
		this.consecutivo = consecutivo;
		this.depositos = depositos;
		this.documento = documento;
		this.fecha = fecha;
		this.saldoanterior = saldoanterior;
		this.valor = valor;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Integer getDepositos() {
		return this.depositos;
	}

	public void setDepositos(Integer depositos) {
		this.depositos = depositos;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Integer getSaldoanterior() {
		return this.saldoanterior;
	}

	public void setSaldoanterior(Integer saldoanterior) {
		this.saldoanterior = saldoanterior;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

}
