package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * TarjetaviajeId generated by hbm2java
 */
public class TarjetaviajeId implements java.io.Serializable {

	private String numerotarjeta;
	private int consecutivoviaje;

	public TarjetaviajeId() {
	}

	public TarjetaviajeId(String numerotarjeta, int consecutivoviaje) {
		this.numerotarjeta = numerotarjeta;
		this.consecutivoviaje = consecutivoviaje;
	}

	public String getNumerotarjeta() {
		return this.numerotarjeta;
	}

	public void setNumerotarjeta(String numerotarjeta) {
		this.numerotarjeta = numerotarjeta;
	}

	public int getConsecutivoviaje() {
		return this.consecutivoviaje;
	}

	public void setConsecutivoviaje(int consecutivoviaje) {
		this.consecutivoviaje = consecutivoviaje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TarjetaviajeId))
			return false;
		TarjetaviajeId castOther = (TarjetaviajeId) other;

		return ((this.getNumerotarjeta() == castOther.getNumerotarjeta())
				|| (this.getNumerotarjeta() != null && castOther.getNumerotarjeta() != null
						&& this.getNumerotarjeta().equals(castOther.getNumerotarjeta())))
				&& (this.getConsecutivoviaje() == castOther.getConsecutivoviaje());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumerotarjeta() == null ? 0 : this.getNumerotarjeta().hashCode());
		result = 37 * result + this.getConsecutivoviaje();
		return result;
	}

}
