package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * TarjetaviajeNew generated by hbm2java
 */
public class TarjetaviajeNew implements java.io.Serializable {

	private TarjetaviajeNewId id;
	private Boolean estado;

	public TarjetaviajeNew() {
	}

	public TarjetaviajeNew(TarjetaviajeNewId id) {
		this.id = id;
	}

	public TarjetaviajeNew(TarjetaviajeNewId id, Boolean estado) {
		this.id = id;
		this.estado = estado;
	}

	public TarjetaviajeNewId getId() {
		return this.id;
	}

	public void setId(TarjetaviajeNewId id) {
		this.id = id;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
