package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta implements java.io.Serializable {

	private String numerotarjeta;
	private Banco banco;
	private Franquicia franquicia;
	private Promotor promotor;
	private int limite;
	private Date fechainicio;
	private Date fechafin;
	private String fechavencimiento;
	private String codseguridad;
	private String tarjetahabiente;
	private String direcciontarjetahabiente;
	private String cedulatarjetahabiente;
	private String telefonotarjetahabiente;
	private Date fechamod;
	private String usuariomod;
	private Boolean tac;
	private Set autovozs = new HashSet(0);
	private Set transaccions = new HashSet(0);
	private Set depositostarjetas = new HashSet(0);
	private Set tarjetaviajes = new HashSet(0);
	private Set saldodepositoses = new HashSet(0);
	private Set auditTarjetaviajes = new HashSet(0);

	public Tarjeta() {
	}

	public Tarjeta(String numerotarjeta, Banco banco, Franquicia franquicia, Promotor promotor, int limite,
			String fechavencimiento, String codseguridad, String tarjetahabiente, String direcciontarjetahabiente,
			String cedulatarjetahabiente, String telefonotarjetahabiente) {
		this.numerotarjeta = numerotarjeta;
		this.banco = banco;
		this.franquicia = franquicia;
		this.promotor = promotor;
		this.limite = limite;
		this.fechavencimiento = fechavencimiento;
		this.codseguridad = codseguridad;
		this.tarjetahabiente = tarjetahabiente;
		this.direcciontarjetahabiente = direcciontarjetahabiente;
		this.cedulatarjetahabiente = cedulatarjetahabiente;
		this.telefonotarjetahabiente = telefonotarjetahabiente;
	}

	public Tarjeta(String numerotarjeta, Banco banco, Franquicia franquicia, Promotor promotor, int limite,
			Date fechainicio, Date fechafin, String fechavencimiento, String codseguridad, String tarjetahabiente,
			String direcciontarjetahabiente, String cedulatarjetahabiente, String telefonotarjetahabiente,
			Date fechamod, String usuariomod, Boolean tac, Set autovozs, Set transaccions, Set depositostarjetas,
			Set tarjetaviajes, Set saldodepositoses, Set auditTarjetaviajes) {
		this.numerotarjeta = numerotarjeta;
		this.banco = banco;
		this.franquicia = franquicia;
		this.promotor = promotor;
		this.limite = limite;
		this.fechainicio = fechainicio;
		this.fechafin = fechafin;
		this.fechavencimiento = fechavencimiento;
		this.codseguridad = codseguridad;
		this.tarjetahabiente = tarjetahabiente;
		this.direcciontarjetahabiente = direcciontarjetahabiente;
		this.cedulatarjetahabiente = cedulatarjetahabiente;
		this.telefonotarjetahabiente = telefonotarjetahabiente;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
		this.tac = tac;
		this.autovozs = autovozs;
		this.transaccions = transaccions;
		this.depositostarjetas = depositostarjetas;
		this.tarjetaviajes = tarjetaviajes;
		this.saldodepositoses = saldodepositoses;
		this.auditTarjetaviajes = auditTarjetaviajes;
	}

	public String getNumerotarjeta() {
		return this.numerotarjeta;
	}

	public void setNumerotarjeta(String numerotarjeta) {
		this.numerotarjeta = numerotarjeta;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Franquicia getFranquicia() {
		return this.franquicia;
	}

	public void setFranquicia(Franquicia franquicia) {
		this.franquicia = franquicia;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public int getLimite() {
		return this.limite;
	}

	public void setLimite(int limite) {
		this.limite = limite;
	}

	public Date getFechainicio() {
		return this.fechainicio;
	}

	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public String getFechavencimiento() {
		return this.fechavencimiento;
	}

	public void setFechavencimiento(String fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

	public String getCodseguridad() {
		return this.codseguridad;
	}

	public void setCodseguridad(String codseguridad) {
		this.codseguridad = codseguridad;
	}

	public String getTarjetahabiente() {
		return this.tarjetahabiente;
	}

	public void setTarjetahabiente(String tarjetahabiente) {
		this.tarjetahabiente = tarjetahabiente;
	}

	public String getDirecciontarjetahabiente() {
		return this.direcciontarjetahabiente;
	}

	public void setDirecciontarjetahabiente(String direcciontarjetahabiente) {
		this.direcciontarjetahabiente = direcciontarjetahabiente;
	}

	public String getCedulatarjetahabiente() {
		return this.cedulatarjetahabiente;
	}

	public void setCedulatarjetahabiente(String cedulatarjetahabiente) {
		this.cedulatarjetahabiente = cedulatarjetahabiente;
	}

	public String getTelefonotarjetahabiente() {
		return this.telefonotarjetahabiente;
	}

	public void setTelefonotarjetahabiente(String telefonotarjetahabiente) {
		this.telefonotarjetahabiente = telefonotarjetahabiente;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Boolean getTac() {
		return this.tac;
	}

	public void setTac(Boolean tac) {
		this.tac = tac;
	}

	public Set getAutovozs() {
		return this.autovozs;
	}

	public void setAutovozs(Set autovozs) {
		this.autovozs = autovozs;
	}

	public Set getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set transaccions) {
		this.transaccions = transaccions;
	}

	public Set getDepositostarjetas() {
		return this.depositostarjetas;
	}

	public void setDepositostarjetas(Set depositostarjetas) {
		this.depositostarjetas = depositostarjetas;
	}

	public Set getTarjetaviajes() {
		return this.tarjetaviajes;
	}

	public void setTarjetaviajes(Set tarjetaviajes) {
		this.tarjetaviajes = tarjetaviajes;
	}

	public Set getSaldodepositoses() {
		return this.saldodepositoses;
	}

	public void setSaldodepositoses(Set saldodepositoses) {
		this.saldodepositoses = saldodepositoses;
	}

	public Set getAuditTarjetaviajes() {
		return this.auditTarjetaviajes;
	}

	public void setAuditTarjetaviajes(Set auditTarjetaviajes) {
		this.auditTarjetaviajes = auditTarjetaviajes;
	}

}
