package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tarjetaviaje generated by hbm2java
 */
public class Tarjetaviaje implements java.io.Serializable {

	private TarjetaviajeId id;
	private Tarjeta tarjeta;
	private Viaje viaje;
	private Boolean estado;
	private Date fechamod;
	private String usuariomod;

	public Tarjetaviaje() {
	}

	public Tarjetaviaje(TarjetaviajeId id, Tarjeta tarjeta, Viaje viaje) {
		this.id = id;
		this.tarjeta = tarjeta;
		this.viaje = viaje;
	}

	public Tarjetaviaje(TarjetaviajeId id, Tarjeta tarjeta, Viaje viaje, Boolean estado, Date fechamod,
			String usuariomod) {
		this.id = id;
		this.tarjeta = tarjeta;
		this.viaje = viaje;
		this.estado = estado;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
	}

	public TarjetaviajeId getId() {
		return this.id;
	}

	public void setId(TarjetaviajeId id) {
		this.id = id;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Viaje getViaje() {
		return this.viaje;
	}

	public void setViaje(Viaje viaje) {
		this.viaje = viaje;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

}
