package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tasadebolivaroficina generated by hbm2java
 */
public class Tasadebolivaroficina implements java.io.Serializable {

	private TasadebolivaroficinaId id;
	private BigDecimal preciobolivar;
	private String usuariomod;
	private Date fechamod;

	public Tasadebolivaroficina() {
	}

	public Tasadebolivaroficina(TasadebolivaroficinaId id) {
		this.id = id;
	}

	public Tasadebolivaroficina(TasadebolivaroficinaId id, BigDecimal preciobolivar, String usuariomod, Date fechamod) {
		this.id = id;
		this.preciobolivar = preciobolivar;
		this.usuariomod = usuariomod;
		this.fechamod = fechamod;
	}

	public TasadebolivaroficinaId getId() {
		return this.id;
	}

	public void setId(TasadebolivaroficinaId id) {
		this.id = id;
	}

	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

}
