package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Tasabolivartransferpais generated by hbm2java
 */
public class Tasabolivartransferpais implements java.io.Serializable {

	private TasabolivartransferpaisId id;
	private Paisiso paisiso;
	private BigDecimal preciobolivar;

	public Tasabolivartransferpais() {
	}

	public Tasabolivartransferpais(TasabolivartransferpaisId id, Paisiso paisiso) {
		this.id = id;
		this.paisiso = paisiso;
	}

	public Tasabolivartransferpais(TasabolivartransferpaisId id, Paisiso paisiso, BigDecimal preciobolivar) {
		this.id = id;
		this.paisiso = paisiso;
		this.preciobolivar = preciobolivar;
	}

	public TasabolivartransferpaisId getId() {
		return this.id;
	}

	public void setId(TasabolivartransferpaisId id) {
		this.id = id;
	}

	public Paisiso getPaisiso() {
		return this.paisiso;
	}

	public void setPaisiso(Paisiso paisiso) {
		this.paisiso = paisiso;
	}

	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

}
