package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Tasabolivarnegociado generated by hbm2java
 */
public class Tasabolivarnegociado implements java.io.Serializable {

	private TasabolivarnegociadoId id;
	private Promotor promotor;
	private BigDecimal preciobolivar;
	private String usuariomod;
	private BigDecimal preciocompra;
	private BigDecimal precioasesor;

	public Tasabolivarnegociado() {
	}

	public Tasabolivarnegociado(TasabolivarnegociadoId id, Promotor promotor) {
		this.id = id;
		this.promotor = promotor;
	}

	public Tasabolivarnegociado(TasabolivarnegociadoId id, Promotor promotor, BigDecimal preciobolivar,
			String usuariomod, BigDecimal preciocompra, BigDecimal precioasesor) {
		this.id = id;
		this.promotor = promotor;
		this.preciobolivar = preciobolivar;
		this.usuariomod = usuariomod;
		this.preciocompra = preciocompra;
		this.precioasesor = precioasesor;
	}

	public TasabolivarnegociadoId getId() {
		return this.id;
	}

	public void setId(TasabolivarnegociadoId id) {
		this.id = id;
	}

	public Promotor getPromotor() {
		return this.promotor;
	}

	public void setPromotor(Promotor promotor) {
		this.promotor = promotor;
	}

	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

	public BigDecimal getPreciocompra() {
		return this.preciocompra;
	}

	public void setPreciocompra(BigDecimal preciocompra) {
		this.preciocompra = preciocompra;
	}

	public BigDecimal getPrecioasesor() {
		return this.precioasesor;
	}

	public void setPrecioasesor(BigDecimal precioasesor) {
		this.precioasesor = precioasesor;
	}

}
