package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tasadolarparametros generated by hbm2java
 */
public class Tasadolarparametros implements java.io.Serializable {

	private TasadolarparametrosId id;
	private Date fechafin;
	private Integer tasadolarcliente;

	public Tasadolarparametros() {
	}

	public Tasadolarparametros(TasadolarparametrosId id) {
		this.id = id;
	}

	public Tasadolarparametros(TasadolarparametrosId id, Date fechafin, Integer tasadolarcliente) {
		this.id = id;
		this.fechafin = fechafin;
		this.tasadolarcliente = tasadolarcliente;
	}

	public TasadolarparametrosId getId() {
		return this.id;
	}

	public void setId(TasadolarparametrosId id) {
		this.id = id;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public Integer getTasadolarcliente() {
		return this.tasadolarcliente;
	}

	public void setTasadolarcliente(Integer tasadolarcliente) {
		this.tasadolarcliente = tasadolarcliente;
	}

}
