package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * Tasadolar generated by hbm2java
 */
public class Tasadolar implements java.io.Serializable {

	private TasadolarId id;
	private Pais pais;
	private BigDecimal tasa;
	private BigDecimal tasadolar;
	private BigDecimal trm;

	public Tasadolar() {
	}

	public Tasadolar(TasadolarId id, Pais pais) {
		this.id = id;
		this.pais = pais;
	}

	public Tasadolar(TasadolarId id, Pais pais, BigDecimal tasa, BigDecimal tasadolar, BigDecimal trm) {
		this.id = id;
		this.pais = pais;
		this.tasa = tasa;
		this.tasadolar = tasadolar;
		this.trm = trm;
	}

	public TasadolarId getId() {
		return this.id;
	}

	public void setId(TasadolarId id) {
		this.id = id;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public BigDecimal getTasa() {
		return this.tasa;
	}

	public void setTasa(BigDecimal tasa) {
		this.tasa = tasa;
	}

	public BigDecimal getTasadolar() {
		return this.tasadolar;
	}

	public void setTasadolar(BigDecimal tasadolar) {
		this.tasadolar = tasadolar;
	}

	public BigDecimal getTrm() {
		return this.trm;
	}

	public void setTrm(BigDecimal trm) {
		this.trm = trm;
	}

}
