package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TasadolarId generated by hbm2java
 */
public class TasadolarId implements java.io.Serializable {

	private String codigopais;
	private Date fecha;

	public TasadolarId() {
	}

	public TasadolarId(String codigopais, Date fecha) {
		this.codigopais = codigopais;
		this.fecha = fecha;
	}

	public String getCodigopais() {
		return this.codigopais;
	}

	public void setCodigopais(String codigopais) {
		this.codigopais = codigopais;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TasadolarId))
			return false;
		TasadolarId castOther = (TasadolarId) other;

		return ((this.getCodigopais() == castOther.getCodigopais()) || (this.getCodigopais() != null
				&& castOther.getCodigopais() != null && this.getCodigopais().equals(castOther.getCodigopais())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodigopais() == null ? 0 : this.getCodigopais().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
