package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Tasadolarbancopais generated by hbm2java
 */
public class Tasadolarbancopais implements java.io.Serializable {

	private TasadolarbancopaisId id;
	private Integer tasacliente;
	private Integer tasaoficina;

	public Tasadolarbancopais() {
	}

	public Tasadolarbancopais(TasadolarbancopaisId id) {
		this.id = id;
	}

	public Tasadolarbancopais(TasadolarbancopaisId id, Integer tasacliente, Integer tasaoficina) {
		this.id = id;
		this.tasacliente = tasacliente;
		this.tasaoficina = tasaoficina;
	}

	public TasadolarbancopaisId getId() {
		return this.id;
	}

	public void setId(TasadolarbancopaisId id) {
		this.id = id;
	}

	public Integer getTasacliente() {
		return this.tasacliente;
	}

	public void setTasacliente(Integer tasacliente) {
		this.tasacliente = tasacliente;
	}

	public Integer getTasaoficina() {
		return this.tasaoficina;
	}

	public void setTasaoficina(Integer tasaoficina) {
		this.tasaoficina = tasaoficina;
	}

}
