package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tasadolarparametrospromotor generated by hbm2java
 */
public class Tasadolarparametrospromotor implements java.io.Serializable {

	private TasadolarparametrospromotorId id;
	private Date fechafin;
	private Integer tasadolar;

	public Tasadolarparametrospromotor() {
	}

	public Tasadolarparametrospromotor(TasadolarparametrospromotorId id) {
		this.id = id;
	}

	public Tasadolarparametrospromotor(TasadolarparametrospromotorId id, Date fechafin, Integer tasadolar) {
		this.id = id;
		this.fechafin = fechafin;
		this.tasadolar = tasadolar;
	}

	public TasadolarparametrospromotorId getId() {
		return this.id;
	}

	public void setId(TasadolarparametrospromotorId id) {
		this.id = id;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

	public Integer getTasadolar() {
		return this.tasadolar;
	}

	public void setTasadolar(Integer tasadolar) {
		this.tasadolar = tasadolar;
	}

}
