package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipogasto generated by hbm2java
 */
public class Tipogasto implements java.io.Serializable {

	private String codtipogasto;
	private String descripcion;
	private String tipo;
	private Set gastoses = new HashSet(0);

	public Tipogasto() {
	}

	public Tipogasto(String codtipogasto) {
		this.codtipogasto = codtipogasto;
	}

	public Tipogasto(String codtipogasto, String descripcion, String tipo, Set gastoses) {
		this.codtipogasto = codtipogasto;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.gastoses = gastoses;
	}

	public String getCodtipogasto() {
		return this.codtipogasto;
	}

	public void setCodtipogasto(String codtipogasto) {
		this.codtipogasto = codtipogasto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getGastoses() {
		return this.gastoses;
	}

	public void setGastoses(Set gastoses) {
		this.gastoses = gastoses;
	}

}
