package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Tipoproceso generated by hbm2java
 */
public class Tipoproceso implements java.io.Serializable {

	private String tipo;
	private String descripcion;

	public Tipoproceso() {
	}

	public Tipoproceso(String tipo) {
		this.tipo = tipo;
	}

	public Tipoproceso(String tipo, String descripcion) {
		this.tipo = tipo;
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
