package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Transaccionerror generated by hbm2java
 */
public class Transaccionerror implements java.io.Serializable {

	private TransaccionerrorId id;

	public Transaccionerror() {
	}

	public Transaccionerror(TransaccionerrorId id) {
		this.id = id;
	}

	public TransaccionerrorId getId() {
		return this.id;
	}

	public void setId(TransaccionerrorId id) {
		this.id = id;
	}

}
