package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Transferencia generated by hbm2java
 */
public class Transferencia implements java.io.Serializable {

	private int consecutivo;
	private Cuentapromotor cuentapromotor;
	private Gastos gastos;
	private BigDecimal preciobolivar;
	private String tipobolivar;
	private Long valorbolivar;
	private String numcuenta;
	private BigDecimal preciocompra;
	private BigDecimal precioasesor;
	private Date fechamod;
	private String usuariomod;

	public Transferencia() {
	}

	public Transferencia(Gastos gastos) {
		this.gastos = gastos;
	}

	public Transferencia(Cuentapromotor cuentapromotor, Gastos gastos, BigDecimal preciobolivar, String tipobolivar,
			Long valorbolivar, String numcuenta, BigDecimal preciocompra, BigDecimal precioasesor, Date fechamod,
			String usuariomod) {
		this.cuentapromotor = cuentapromotor;
		this.gastos = gastos;
		this.preciobolivar = preciobolivar;
		this.tipobolivar = tipobolivar;
		this.valorbolivar = valorbolivar;
		this.numcuenta = numcuenta;
		this.preciocompra = preciocompra;
		this.precioasesor = precioasesor;
		this.fechamod = fechamod;
		this.usuariomod = usuariomod;
	}

	public int getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(int consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Cuentapromotor getCuentapromotor() {
		return this.cuentapromotor;
	}

	public void setCuentapromotor(Cuentapromotor cuentapromotor) {
		this.cuentapromotor = cuentapromotor;
	}

	public Gastos getGastos() {
		return this.gastos;
	}

	public void setGastos(Gastos gastos) {
		this.gastos = gastos;
	}

	public BigDecimal getPreciobolivar() {
		return this.preciobolivar;
	}

	public void setPreciobolivar(BigDecimal preciobolivar) {
		this.preciobolivar = preciobolivar;
	}

	public String getTipobolivar() {
		return this.tipobolivar;
	}

	public void setTipobolivar(String tipobolivar) {
		this.tipobolivar = tipobolivar;
	}

	public Long getValorbolivar() {
		return this.valorbolivar;
	}

	public void setValorbolivar(Long valorbolivar) {
		this.valorbolivar = valorbolivar;
	}

	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	public BigDecimal getPreciocompra() {
		return this.preciocompra;
	}

	public void setPreciocompra(BigDecimal preciocompra) {
		this.preciocompra = preciocompra;
	}

	public BigDecimal getPrecioasesor() {
		return this.precioasesor;
	}

	public void setPrecioasesor(BigDecimal precioasesor) {
		this.precioasesor = precioasesor;
	}

	public Date getFechamod() {
		return this.fechamod;
	}

	public void setFechamod(Date fechamod) {
		this.fechamod = fechamod;
	}

	public String getUsuariomod() {
		return this.usuariomod;
	}

	public void setUsuariomod(String usuariomod) {
		this.usuariomod = usuariomod;
	}

}
