package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private String usuario;
	private String nombre;
	private String clave;
	private Boolean activo;
	private Boolean administrador;
	private Set rols = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String usuario) {
		this.usuario = usuario;
	}

	public Usuario(String usuario, String nombre, String clave, Boolean activo, Boolean administrador, Set rols) {
		this.usuario = usuario;
		this.nombre = nombre;
		this.clave = clave;
		this.activo = activo;
		this.administrador = administrador;
		this.rols = rols;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public Boolean getAdministrador() {
		return this.administrador;
	}

	public void setAdministrador(Boolean administrador) {
		this.administrador = administrador;
	}

	public Set getRols() {
		return this.rols;
	}

	public void setRols(Set rols) {
		this.rols = rols;
	}

}
