package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Variable generated by hbm2java
 */
public class Variable implements java.io.Serializable {

	private int numregistro;
	private BigDecimal preciodolarven;
	private Date fechaini;
	private Date fechafin;

	public Variable() {
	}

	public Variable(int numregistro) {
		this.numregistro = numregistro;
	}

	public Variable(int numregistro, BigDecimal preciodolarven, Date fechaini, Date fechafin) {
		this.numregistro = numregistro;
		this.preciodolarven = preciodolarven;
		this.fechaini = fechaini;
		this.fechafin = fechafin;
	}

	public int getNumregistro() {
		return this.numregistro;
	}

	public void setNumregistro(int numregistro) {
		this.numregistro = numregistro;
	}

	public BigDecimal getPreciodolarven() {
		return this.preciodolarven;
	}

	public void setPreciodolarven(BigDecimal preciodolarven) {
		this.preciodolarven = preciodolarven;
	}

	public Date getFechaini() {
		return this.fechaini;
	}

	public void setFechaini(Date fechaini) {
		this.fechaini = fechaini;
	}

	public Date getFechafin() {
		return this.fechafin;
	}

	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
