package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistacuentasaldo generated by hbm2java
 */
public class Vistacuentasaldo implements java.io.Serializable {

	private VistacuentasaldoId id;

	public Vistacuentasaldo() {
	}

	public Vistacuentasaldo(VistacuentasaldoId id) {
		this.id = id;
	}

	public VistacuentasaldoId getId() {
		return this.id;
	}

	public void setId(VistacuentasaldoId id) {
		this.id = id;
	}

}
