package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistatxdiasemana generated by hbm2java
 */
public class Vistatxdiasemana implements java.io.Serializable {

	private VistatxdiasemanaId id;

	public Vistatxdiasemana() {
	}

	public Vistatxdiasemana(VistatxdiasemanaId id) {
		this.id = id;
	}

	public VistatxdiasemanaId getId() {
		return this.id;
	}

	public void setId(VistatxdiasemanaId id) {
		this.id = id;
	}

}
