package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldomartes generated by hbm2java
 */
public class Vistasaldomartes implements java.io.Serializable {

	private VistasaldomartesId id;

	public Vistasaldomartes() {
	}

	public Vistasaldomartes(VistasaldomartesId id) {
		this.id = id;
	}

	public VistasaldomartesId getId() {
		return this.id;
	}

	public void setId(VistasaldomartesId id) {
		this.id = id;
	}

}
