package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistacuentadetalle generated by hbm2java
 */
public class Vistacuentadetalle implements java.io.Serializable {

	private VistacuentadetalleId id;

	public Vistacuentadetalle() {
	}

	public Vistacuentadetalle(VistacuentadetalleId id) {
		this.id = id;
	}

	public VistacuentadetalleId getId() {
		return this.id;
	}

	public void setId(VistacuentadetalleId id) {
		this.id = id;
	}

}
