package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistacuentasvenezolanas generated by hbm2java
 */
public class Vistacuentasvenezolanas implements java.io.Serializable {

	private VistacuentasvenezolanasId id;

	public Vistacuentasvenezolanas() {
	}

	public Vistacuentasvenezolanas(VistacuentasvenezolanasId id) {
		this.id = id;
	}

	public VistacuentasvenezolanasId getId() {
		return this.id;
	}

	public void setId(VistacuentasvenezolanasId id) {
		this.id = id;
	}

}
