package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * VistacuentaId generated by hbm2java
 */
public class VistacuentaId implements java.io.Serializable {

	private String numcuenta;
	private Date fecha;

	public VistacuentaId() {
	}

	public VistacuentaId(String numcuenta, Date fecha) {
		this.numcuenta = numcuenta;
		this.fecha = fecha;
	}

	public String getNumcuenta() {
		return this.numcuenta;
	}

	public void setNumcuenta(String numcuenta) {
		this.numcuenta = numcuenta;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistacuentaId))
			return false;
		VistacuentaId castOther = (VistacuentaId) other;

		return ((this.getNumcuenta() == castOther.getNumcuenta()) || (this.getNumcuenta() != null
				&& castOther.getNumcuenta() != null && this.getNumcuenta().equals(castOther.getNumcuenta())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumcuenta() == null ? 0 : this.getNumcuenta().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
