package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldolunes generated by hbm2java
 */
public class Vistasaldolunes implements java.io.Serializable {

	private VistasaldolunesId id;

	public Vistasaldolunes() {
	}

	public Vistasaldolunes(VistasaldolunesId id) {
		this.id = id;
	}

	public VistasaldolunesId getId() {
		return this.id;
	}

	public void setId(VistasaldolunesId id) {
		this.id = id;
	}

}
