package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistacuentasfecha generated by hbm2java
 */
public class Vistacuentasfecha implements java.io.Serializable {

	private VistacuentasfechaId id;

	public Vistacuentasfecha() {
	}

	public Vistacuentasfecha(VistacuentasfechaId id) {
		this.id = id;
	}

	public VistacuentasfechaId getId() {
		return this.id;
	}

	public void setId(VistacuentasfechaId id) {
		this.id = id;
	}

}
