package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasemanasanio generated by hbm2java
 */
public class Vistasemanasanio implements java.io.Serializable {

	private VistasemanasanioId id;

	public Vistasemanasanio() {
	}

	public Vistasemanasanio(VistasemanasanioId id) {
		this.id = id;
	}

	public VistasemanasanioId getId() {
		return this.id;
	}

	public void setId(VistasemanasanioId id) {
		this.id = id;
	}

}
