package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistacuentacons generated by hbm2java
 */
public class Vistacuentacons implements java.io.Serializable {

	private VistacuentaconsId id;

	public Vistacuentacons() {
	}

	public Vistacuentacons(VistacuentaconsId id) {
		this.id = id;
	}

	public VistacuentaconsId getId() {
		return this.id;
	}

	public void setId(VistacuentaconsId id) {
		this.id = id;
	}

}
