package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldoviernes generated by hbm2java
 */
public class Vistasaldoviernes implements java.io.Serializable {

	private VistasaldoviernesId id;

	public Vistasaldoviernes() {
	}

	public Vistasaldoviernes(VistasaldoviernesId id) {
		this.id = id;
	}

	public VistasaldoviernesId getId() {
		return this.id;
	}

	public void setId(VistasaldoviernesId id) {
		this.id = id;
	}

}
