package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistaactivaciones generated by hbm2java
 */
public class Vistaactivaciones implements java.io.Serializable {

	private VistaactivacionesId id;

	public Vistaactivaciones() {
	}

	public Vistaactivaciones(VistaactivacionesId id) {
		this.id = id;
	}

	public VistaactivacionesId getId() {
		return this.id;
	}

	public void setId(VistaactivacionesId id) {
		this.id = id;
	}

}
