package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldomiercoles generated by hbm2java
 */
public class Vistasaldomiercoles implements java.io.Serializable {

	private VistasaldomiercolesId id;

	public Vistasaldomiercoles() {
	}

	public Vistasaldomiercoles(VistasaldomiercolesId id) {
		this.id = id;
	}

	public VistasaldomiercolesId getId() {
		return this.id;
	}

	public void setId(VistasaldomiercolesId id) {
		this.id = id;
	}

}
