package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * VistaactobservacionId generated by hbm2java
 */
public class VistaactobservacionId implements java.io.Serializable {

	private String tipo;
	private Integer consecutivo;
	private Date fecha;
	private String observacion;
	private String dato;

	public VistaactobservacionId() {
	}

	public VistaactobservacionId(String tipo, Integer consecutivo, Date fecha, String observacion, String dato) {
		this.tipo = tipo;
		this.consecutivo = consecutivo;
		this.fecha = fecha;
		this.observacion = observacion;
		this.dato = dato;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getDato() {
		return this.dato;
	}

	public void setDato(String dato) {
		this.dato = dato;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaactobservacionId))
			return false;
		VistaactobservacionId castOther = (VistaactobservacionId) other;

		return ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null && castOther.getTipo() != null
				&& this.getTipo().equals(castOther.getTipo())))
				&& ((this.getConsecutivo() == castOther.getConsecutivo())
						|| (this.getConsecutivo() != null && castOther.getConsecutivo() != null
								&& this.getConsecutivo().equals(castOther.getConsecutivo())))
				&& ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha().equals(castOther.getFecha())))
				&& ((this.getObservacion() == castOther.getObservacion())
						|| (this.getObservacion() != null && castOther.getObservacion() != null
								&& this.getObservacion().equals(castOther.getObservacion())))
				&& ((this.getDato() == castOther.getDato()) || (this.getDato() != null && castOther.getDato() != null
						&& this.getDato().equals(castOther.getDato())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result + (getConsecutivo() == null ? 0 : this.getConsecutivo().hashCode());
		result = 37 * result + (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result + (getObservacion() == null ? 0 : this.getObservacion().hashCode());
		result = 37 * result + (getDato() == null ? 0 : this.getDato().hashCode());
		return result;
	}

}
