package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistacuenta generated by hbm2java
 */
public class Vistacuenta implements java.io.Serializable {

	private VistacuentaId id;

	public Vistacuenta() {
	}

	public Vistacuenta(VistacuentaId id) {
		this.id = id;
	}

	public VistacuentaId getId() {
		return this.id;
	}

	public void setId(VistacuentaId id) {
		this.id = id;
	}

}
