package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldojueves generated by hbm2java
 */
public class Vistasaldojueves implements java.io.Serializable {

	private VistasaldojuevesId id;

	public Vistasaldojueves() {
	}

	public Vistasaldojueves(VistasaldojuevesId id) {
		this.id = id;
	}

	public VistasaldojuevesId getId() {
		return this.id;
	}

	public void setId(VistasaldojuevesId id) {
		this.id = id;
	}

}
