package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldodiariopromotor generated by hbm2java
 */
public class Vistasaldodiariopromotor implements java.io.Serializable {

	private VistasaldodiariopromotorId id;

	public Vistasaldodiariopromotor() {
	}

	public Vistasaldodiariopromotor(VistasaldodiariopromotorId id) {
		this.id = id;
	}

	public VistasaldodiariopromotorId getId() {
		return this.id;
	}

	public void setId(VistasaldodiariopromotorId id) {
		this.id = id;
	}

}
