package com.monedafrontera.dto;
// Generated 5/11/2015 11:46:49 AM by Hibernate Tools 4.3.1.Final

/**
 * Vistasaldosabado generated by hbm2java
 */
public class Vistasaldosabado implements java.io.Serializable {

	private VistasaldosabadoId id;

	public Vistasaldosabado() {
	}

	public Vistasaldosabado(VistasaldosabadoId id) {
		this.id = id;
	}

	public VistasaldosabadoId getId() {
		return this.id;
	}

	public void setId(VistasaldosabadoId id) {
		this.id = id;
	}

}
